/// <reference types="vite/client" />

// Pull the generated `BrikaI18n.Namespaces` global augmentation into the
// compilation graph. The file is regenerated by `bun run i18n:types` (also
// runs on `postinstall`) and by the dev plugin on every locale-file edit.
// Lives in `node_modules/.cache/` so it stays out of the source tree;
// because the augmentation targets a *global* namespace, location doesn't
// matter — any `.d.ts` referenced anywhere in the compilation merges into
// the same `BrikaI18n.Namespaces` interface.
//
// If `tsc` reports "Cannot find file", run `bun run i18n:types` to populate
// the cache after a fresh checkout.
/// <reference path="../../../node_modules/.cache/@brika/i18n-devtools/i18n-registry.d.ts" />
