import { isPlainObject } from './object';

// ─── Helpers ────────────────────────────────────────────────────────────────

// PascalCase + strip any character that isn't valid in a TS identifier. Plugin
// namespaces look like `plugin:@brika/blocks-builtin` — without sanitisation
// `toTypeName` would emit `Plugin:@brika/blocksBuiltinNs`, which is a syntax
// error in an interface name.
function toTypeName(name: string): string {
  const pascal = name
    .replaceAll(/(?:^|[^a-zA-Z0-9])([a-zA-Z0-9])/g, (_, c: string) => c.toUpperCase())
    .replaceAll(/[^a-zA-Z0-9_$]/g, '');
  return `${pascal}Ns`;
}

function isBareKey(key: string): boolean {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key);
}

function safeKey(key: string): string {
  return isBareKey(key) ? key : `"${key}"`;
}

function toTypeString(value: unknown, indent: number): string {
  if (Array.isArray(value)) {
    return 'readonly string[]';
  }
  if (!isPlainObject(value)) {
    return 'string';
  }
  const entries = Object.entries(value);
  if (entries.length === 0) {
    return 'Record<string, string>';
  }
  const pad = '\t'.repeat(indent + 1);
  const closePad = '\t'.repeat(indent);
  const lines = entries
    .toSorted(([a], [b]) => a.localeCompare(b))
    .map(([key, val]) => `${pad}${safeKey(key)}: ${toTypeString(val, indent + 1)};`);
  return `{\n${lines.join('\n')}\n${closePad}}`;
}

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * Generate `i18n-resources.d.ts` content from namespace data.
 */
export function generateResourceTypes(
  namespaces: { name: string; content: Record<string, unknown> }[]
): string {
  const lines: string[] = [
    '// Auto-generated by @brika/i18n-devtools — do not edit manually',
    '',
    'declare namespace I18nResources {',
  ];

  for (const { name, content } of namespaces) {
    lines.push(`\texport interface ${toTypeName(name)} ${toTypeString(content, 1)}`, '');
  }

  lines.push(
    '}',
    '',
    '/** All core i18n resources keyed by namespace name. */',
    'type I18nResourceMap = {'
  );

  for (const { name } of namespaces) {
    lines.push(`\t${safeKey(name)}: I18nResources.${toTypeName(name)};`);
  }

  lines.push('};', '');

  return lines.join('\n');
}

export interface RegistryAugmentationOptions {
  /**
   * Global namespace whose `Namespaces` interface is widened by the generated
   * augmentation. Defaults to `BrikaI18n` — matching the global the
   * `@brika/i18n` runtime declares.
   *
   * **Why global** instead of `declare module '<module>'`: module
   * augmentation only merges when the augmenting file can resolve the
   * augmented module specifier. Files generated into `node_modules/.cache/`
   * cannot walk up to `node_modules/@brika/i18n` and the augmentation
   * silently fails. A global namespace dodges module resolution — any `.d.ts`
   * in the compilation graph, anywhere on disk, merges into the same
   * interface.
   */
  globalNamespace?: string;
  /** Interface name within the global namespace. Defaults to `Namespaces`. */
  interfaceName?: string;
}

/**
 * Generate a module augmentation that exposes each namespace's key tree to
 * TypeScript. Consumers point this at whichever runtime module they want to
 * augment — defaults to `@brika/i18n/registry` for Brika apps.
 */
export function generateRegistryAugmentation(
  namespaces: { name: string; content: Record<string, unknown> }[],
  options: RegistryAugmentationOptions = {}
): string {
  const globalNamespace = options.globalNamespace ?? 'BrikaI18n';
  const interfaceName = options.interfaceName ?? 'Namespaces';

  // Global namespace augmentation. The trailing `export {};` makes the file a
  // module, which is what lets `declare global { ... }` work — without it,
  // the file is already at top level and the `declare global` block is
  // redundant/invalid. Inside a module, `declare global` is the canonical
  // way to merge into a global interface.
  const lines: string[] = [
    '// Auto-generated by @brika/i18n-devtools — do not edit manually',
    '',
    'declare global {',
    `\tnamespace ${globalNamespace} {`,
    `\t\tinterface ${interfaceName} {`,
  ];

  const ordered = [...namespaces].sort((a, b) => a.name.localeCompare(b.name));
  for (const { name, content } of ordered) {
    lines.push(`\t\t\t${safeKey(name)}: ${toTypeString(content, 3)};`);
  }

  lines.push('\t\t}', '\t}', '}', '', 'export {};', '');

  return lines.join('\n');
}

/**
 * Generate `i18n-namespaces.ts` content from namespace names. The caller's
 * `defaultNamespace` is placed first regardless of whether it appears in the
 * input list — matching i18next's contract that the default namespace is
 * always implicit. Other namespaces follow in input order.
 */
export function generateNamespaceList(nsNames: string[], defaultNamespace = 'translation'): string {
  const ordered = [defaultNamespace, ...nsNames.filter((n) => n !== defaultNamespace)];
  const quotedNames = ordered.map((n) => `'${n}'`).join(', ');
  return [
    '// Auto-generated by @brika/i18n-devtools — do not edit manually',
    '',
    '/**',
    ' * All core i18n namespace names, with the default namespace first.',
    ' */',
    `export const i18nNamespaces = [${quotedNames}] as const;`,
    '',
  ].join('\n');
}
