import { describe, expect, it } from 'bun:test';
import { generateNamespaceList, generateResourceTypes } from './generate';

describe('generateResourceTypes', () => {
	it('returns a valid skeleton with an empty namespace array', () => {
		const result = generateResourceTypes([]);

		expect(result).toContain('declare namespace I18nResources {');
		expect(result).toContain('type I18nResourceMap = {');
		// The namespace body and resource map should both be empty
		expect(result).toContain('declare namespace I18nResources {\n}');
		expect(result).toContain('type I18nResourceMap = {\n};');
	});

	it('generates a flat interface for a single namespace with string values', () => {
		const result = generateResourceTypes([
			{ name: 'common', content: { hello: 'Hello', goodbye: 'Goodbye' } },
		]);

		// Interface naming: "common" -> "CommonNs"
		expect(result).toContain('export interface CommonNs');
		// Keys should be bare (no quoting needed) and typed as string
		expect(result).toContain('goodbye: string;');
		expect(result).toContain('hello: string;');
		// The resource map should reference the interface
		expect(result).toContain('common: I18nResources.CommonNs;');
	});

	it('generates nested object types for nested content', () => {
		const result = generateResourceTypes([
			{
				name: 'dashboard',
				content: {
					header: {
						title: 'Dashboard',
						subtitle: 'Welcome',
					},
					footer: 'Footer text',
				},
			},
		]);

		expect(result).toContain('export interface DashboardNs');
		// "footer" is a plain string, "header" is an object
		expect(result).toContain('footer: string;');
		expect(result).toContain('header: {');
		expect(result).toContain('subtitle: string;');
		expect(result).toContain('title: string;');
	});

	it('types array values as readonly string[]', () => {
		const result = generateResourceTypes([
			{
				name: 'settings',
				content: {
					options: ['one', 'two', 'three'],
					label: 'Settings',
				},
			},
		]);

		expect(result).toContain('export interface SettingsNs');
		expect(result).toContain('label: string;');
		expect(result).toContain('options: readonly string[];');
	});

	it('quotes keys that are not valid JS identifiers', () => {
		const result = generateResourceTypes([
			{
				name: 'common',
				content: {
					'my-key': 'value',
					'another.key': 'value',
					validKey: 'value',
					'123start': 'value',
				},
			},
		]);

		// Hyphenated and dotted keys must be quoted
		expect(result).toContain('"my-key": string;');
		expect(result).toContain('"another.key": string;');
		expect(result).toContain('"123start": string;');
		// Valid identifiers should not be quoted
		expect(result).toContain('validKey: string;');
		expect(result).not.toContain('"validKey"');
	});

	it('generates multiple interfaces and resource map entries for multiple namespaces', () => {
		const result = generateResourceTypes([
			{ name: 'common', content: { ok: 'OK' } },
			{ name: 'dashboard', content: { title: 'Dashboard' } },
			{ name: 'user-settings', content: { theme: 'dark' } },
		]);

		// All interfaces present
		expect(result).toContain('export interface CommonNs');
		expect(result).toContain('export interface DashboardNs');
		expect(result).toContain('export interface UserSettingsNs');

		// Resource map entries
		expect(result).toContain('common: I18nResources.CommonNs;');
		expect(result).toContain('dashboard: I18nResources.DashboardNs;');
		// "user-settings" key needs quoting in the map
		expect(result).toContain('"user-settings": I18nResources.UserSettingsNs;');
	});

	it('sorts keys alphabetically within an interface', () => {
		const result = generateResourceTypes([
			{ name: 'common', content: { zebra: 'Z', alpha: 'A', middle: 'M' } },
		]);

		const alphaIdx = result.indexOf('alpha: string;');
		const middleIdx = result.indexOf('middle: string;');
		const zebraIdx = result.indexOf('zebra: string;');

		expect(alphaIdx).toBeGreaterThan(-1);
		expect(middleIdx).toBeGreaterThan(alphaIdx);
		expect(zebraIdx).toBeGreaterThan(middleIdx);
	});

	it('produces Record<string, string> for empty object values', () => {
		const result = generateResourceTypes([
			{ name: 'empty', content: { section: {} } },
		]);

		expect(result).toContain('section: Record<string, string>;');
	});

	it('treats null and undefined values as string', () => {
		const result = generateResourceTypes([
			{
				name: 'misc',
				content: { nullable: null, undef: undefined },
			},
		]);

		expect(result).toContain('nullable: string;');
		expect(result).toContain('undef: string;');
	});

	it('starts with the auto-generated comment', () => {
		const result = generateResourceTypes([]);
		expect(result.startsWith('// Auto-generated by @brika/i18n-devtools')).toBe(true);
	});

	it('handles deeply nested structures', () => {
		const result = generateResourceTypes([
			{
				name: 'deep',
				content: {
					level1: {
						level2: {
							level3: 'leaf',
						},
					},
				},
			},
		]);

		expect(result).toContain('level1: {');
		expect(result).toContain('level2: {');
		expect(result).toContain('level3: string;');
	});

	it('converts kebab-case and snake_case namespace names to PascalCase type names', () => {
		const result = generateResourceTypes([
			{ name: 'my-long-name', content: { a: '1' } },
			{ name: 'another_name', content: { b: '2' } },
		]);

		expect(result).toContain('export interface MyLongNameNs');
		expect(result).toContain('export interface AnotherNameNs');
	});
});

describe('generateNamespaceList', () => {
	it('puts common first when multiple namespaces are given', () => {
		const result = generateNamespaceList(['dashboard', 'common', 'settings']);

		expect(result).toContain("export const i18nNamespaces = ['common', 'dashboard', 'settings'] as const;");
	});

	it('still includes common first even when it is not in the input', () => {
		const result = generateNamespaceList(['dashboard', 'settings']);

		// 'common' is always prepended
		expect(result).toContain("'common'");
		const commonIdx = result.indexOf("'common'");
		const dashboardIdx = result.indexOf("'dashboard'");
		expect(commonIdx).toBeLessThan(dashboardIdx);
	});

	it('produces a single-element array when only common is provided', () => {
		const result = generateNamespaceList(['common']);

		expect(result).toContain("export const i18nNamespaces = ['common'] as const;");
	});

	it('does not duplicate common', () => {
		const result = generateNamespaceList(['common', 'other']);

		const matches = result.match(/'common'/g);
		expect(matches).toHaveLength(1);
	});

	it('preserves the original order of non-common namespaces', () => {
		const result = generateNamespaceList(['zebra', 'alpha', 'common', 'middle']);

		// After common is moved first, the rest keep their relative order
		expect(result).toContain("['common', 'zebra', 'alpha', 'middle']");
	});

	it('starts with the auto-generated comment', () => {
		const result = generateNamespaceList(['common']);
		expect(result.startsWith('// Auto-generated by @brika/i18n-devtools')).toBe(true);
	});

	it('includes the doc comment', () => {
		const result = generateNamespaceList(['common']);
		expect(result).toContain('* All core i18n namespace names, with the default namespace first.');
	});

	it('uses as const assertion', () => {
		const result = generateNamespaceList(['common']);
		expect(result).toContain('as const;');
	});

	it('ends with a trailing newline', () => {
		const result = generateNamespaceList(['common']);
		expect(result.endsWith('\n')).toBe(true);
	});
});
