// ─── Helpers ────────────────────────────────────────────────────────────────

function toTypeName(name: string): string {
  const pascal = name
    .replaceAll(/(?:^|[-_])([a-z])/g, (_, c: string) => c.toUpperCase())
    .replaceAll(/[-_]/g, '');
  return `${pascal}Ns`;
}

function isBareKey(key: string): boolean {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key);
}

function safeKey(key: string): string {
  return isBareKey(key) ? key : `"${key}"`;
}

function toTypeString(value: unknown, indent: number): string {
  if (value === null || value === undefined || typeof value !== 'object') {
    return 'string';
  }
  if (Array.isArray(value)) {
    return 'readonly string[]';
  }
  const entries = Object.entries(value as Record<string, unknown>);
  if (entries.length === 0) {
    return 'Record<string, string>';
  }
  const pad = '\t'.repeat(indent + 1);
  const closePad = '\t'.repeat(indent);
  const lines = entries
    .toSorted(([a], [b]) => a.localeCompare(b))
    .map(([key, val]) => `${pad}${safeKey(key)}: ${toTypeString(val, indent + 1)};`);
  return `{\n${lines.join('\n')}\n${closePad}}`;
}

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * Generate `i18n-resources.d.ts` content from namespace data.
 */
export function generateResourceTypes(
  namespaces: { name: string; content: Record<string, unknown> }[]
): string {
  const lines: string[] = [
    '// Auto-generated by @brika/i18n-devtools — do not edit manually',
    '',
    'declare namespace I18nResources {',
  ];

  for (const { name, content } of namespaces) {
    lines.push(`\texport interface ${toTypeName(name)} ${toTypeString(content, 1)}`, '');
  }

  lines.push('}', '', '/** All core i18n resources keyed by namespace name. */', 'type I18nResourceMap = {');

  for (const { name } of namespaces) {
    lines.push(`\t${safeKey(name)}: I18nResources.${toTypeName(name)};`);
  }

  lines.push('};', '');

  return lines.join('\n');
}

/**
 * Generate `i18n-namespaces.ts` content from namespace names.
 */
export function generateNamespaceList(nsNames: string[]): string {
  const ordered = ['common', ...nsNames.filter((n) => n !== 'common')];
  const quotedNames = ordered.map((n) => `'${n}'`).join(', ');
  return [
    '// Auto-generated by @brika/i18n-devtools — do not edit manually',
    '',
    '/**',
    ' * All core i18n namespace names, with the default namespace first.',
    ' */',
    `export const i18nNamespaces = [${quotedNames}] as const;`,
    '',
  ].join('\n');
}
