/**
 * Clay's token registry — single source of truth for every CSS custom
 * property that participates in theming.
 *
 * Step 1 covers the ~100 tokens that exist in `clay.css` today (Layer 0
 * scalars, Layer 1 roles, Layer 2 component overrides for color / radius /
 * shadow / corner-shape). Step 4 of the rollout expands Layer 2 to cover
 * border / typography / focus / motion / state for every component.
 *
 * Hand-edit only this file. The two CSS files in `src/styles/tokens-*.css`
 * are generated; rerun `pnpm --filter @brika/clay build:tokens`.
 */

import {
  borderTokens,
  controlSurfaceTokens,
  focusTokens,
  geometryTokens,
  meta,
  motionTokens,
  stateTokens,
  typographyTokens,
} from './expand';
import { inferTokenType } from './infer';
import type { ResolvedTokenSpec, TokenSpec } from './types';

// ─────────────────────────────────────────────────────────────
// Layer 0 — Scalars
// One knob per concern. Themes set these; everything downstream cascades.
// ─────────────────────────────────────────────────────────────
const SCALARS: readonly TokenSpec[] = [
  {
    name: 'radius',
    layer: 'scalar',
    category: 'geometry',
    defaultLight: '0.75rem',
    description: 'Base corner radius. Drives the entire semantic radius scale.',
    themePath: 'geometry.radius',
  },
  {
    name: 'spacing',
    layer: 'scalar',
    category: 'geometry',
    defaultLight: '0.25rem',
    description: 'Base spacing step. Drives Tailwind p-/m-/gap-/size-* utilities.',
    themePath: 'geometry.spacing',
  },
  {
    name: 'text-base',
    layer: 'scalar',
    category: 'typography',
    defaultLight: '1rem',
    description: 'Reference font size. Rescales the entire typography scale.',
    themePath: 'geometry.textBase',
  },
  {
    name: 'font-sans',
    layer: 'scalar',
    category: 'typography',
    defaultLight: '"Inter", ui-sans-serif, system-ui, sans-serif',
    description: 'Default UI typeface for body and controls.',
    themePath: 'geometry.fontSans',
    tailwindNamespace: 'font',
    utilityAlias: 'sans',
  },
  {
    name: 'font-mono',
    layer: 'scalar',
    category: 'typography',
    defaultLight: '"JetBrains Mono", ui-monospace, SFMono-Regular, monospace',
    description: 'Monospace typeface for code and tabular content.',
    themePath: 'geometry.fontMono',
    tailwindNamespace: 'font',
    utilityAlias: 'mono',
  },
  {
    name: 'border-width',
    layer: 'scalar',
    category: 'border',
    defaultLight: '1px',
    description: 'Default border width. Honored by the bare `border` utility.',
    themePath: 'borders.width',
    tailwindNamespace: 'default',
    utilityAlias: 'border-width',
  },
  {
    name: 'ring-width',
    layer: 'scalar',
    category: 'focus',
    defaultLight: '2px',
    description: 'Default focus ring width. Used by the `ring-themed` utility.',
    themePath: 'focus.width',
  },
  {
    name: 'ring-offset',
    layer: 'scalar',
    category: 'focus',
    defaultLight: '2px',
    description: 'Default focus ring offset. Used by `ring-themed`.',
    themePath: 'focus.offset',
  },
  {
    name: 'motion-duration',
    layer: 'scalar',
    category: 'motion',
    defaultLight: '220ms',
    description: 'Base transition duration. Derived motion channels scale from this.',
    themePath: 'motion.duration',
  },
  {
    name: 'motion-easing',
    layer: 'scalar',
    category: 'motion',
    defaultLight: 'cubic-bezier(0.16, 1, 0.3, 1)',
    description: 'Base transition easing. Used by the `ease-standard` utility.',
    themePath: 'motion.easing',
  },
  {
    name: 'backdrop-blur',
    layer: 'scalar',
    category: 'elevation',
    defaultLight: '8px',
    description: 'Default backdrop blur. Honored by `backdrop-blur-theme`.',
    themePath: 'geometry.backdropBlur',
    tailwindNamespace: 'blur',
    utilityAlias: 'theme',
  },
  // Glass — translucent tint applied above floating surfaces. Themes set
  // a soft `rgba(...)` to make tinted-glass effects (e.g. iOS-style
  // frosted panels). `transparent` by default so it's a no-op.
  {
    name: 'glass-tint',
    layer: 'scalar',
    category: 'color',
    defaultLight: 'transparent',
    description: 'Tint colour layered above blurred surfaces. Use rgba/oklch with alpha.',
    themePath: 'glass.tint',
  },
  // Numeric shadow scale — ensures the cascade resolves regardless of
  // Tailwind preflight behaviour. The semantic shadows
  // (`shadow-surface/raised/overlay/modal/spotlight`) reference these.
  // Themes can flatten them all to `none` (Brutalist/Terminal) or push
  // them harder (Skeuomorph) without touching Tailwind.
  {
    name: 'shadow-xs',
    layer: 'role',
    category: 'elevation',
    defaultLight: '0 1px rgb(0 0 0 / 0.05)',
    description: 'Smallest numeric shadow. Underpins `shadow-surface`.',
    tailwindNamespace: 'shadow',
    utilityAlias: 'xs',
  },
  {
    name: 'shadow-sm',
    layer: 'role',
    category: 'elevation',
    defaultLight: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
    description: 'Small numeric shadow. Underpins `shadow-raised`.',
    tailwindNamespace: 'shadow',
    utilityAlias: 'sm',
  },
  {
    name: 'shadow-md',
    layer: 'role',
    category: 'elevation',
    defaultLight: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    description: 'Medium numeric shadow. Underpins `shadow-overlay`.',
    tailwindNamespace: 'shadow',
    utilityAlias: 'md',
  },
  {
    name: 'shadow-lg',
    layer: 'role',
    category: 'elevation',
    defaultLight: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
    description: 'Large numeric shadow. Underpins `shadow-modal`.',
    tailwindNamespace: 'shadow',
    utilityAlias: 'lg',
  },
  {
    name: 'shadow-xl',
    layer: 'role',
    category: 'elevation',
    defaultLight: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
    description: 'Extra-large numeric shadow. Underpins `shadow-spotlight`.',
    tailwindNamespace: 'shadow',
    utilityAlias: 'xl',
  },
  {
    name: 'shadow-2xl',
    layer: 'role',
    category: 'elevation',
    defaultLight: '0 25px 50px -12px rgb(0 0 0 / 0.25)',
    description: 'Heaviest numeric shadow. Skeuomorph-style elevation.',
    tailwindNamespace: 'shadow',
    utilityAlias: '2xl',
  },
];

// ─────────────────────────────────────────────────────────────
// Layer 1 — Color roles
// Themes typically override these. Listed in the order they appear in
// existing presets to make migration mechanical.
// ─────────────────────────────────────────────────────────────
const COLOR_ROLES: readonly TokenSpec[] = [
  {
    name: 'background',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.99 0 0)',
    defaultDark: 'oklch(0.14 0.02 260)',
    description: 'Page background. The base canvas every surface sits on.',
    themePath: 'colors.background',
    tailwindNamespace: 'color',
  },
  {
    name: 'foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.15 0.01 260)',
    defaultDark: 'oklch(0.96 0.01 260)',
    description: 'Default text color, paired with `background`.',
    themePath: 'colors.foreground',
    tailwindNamespace: 'color',
  },
  {
    name: 'card',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(1 0 0)',
    defaultDark: 'oklch(0.17 0.02 260)',
    description: 'Background for resting cards and panels.',
    themePath: 'colors.card',
    tailwindNamespace: 'color',
  },
  {
    name: 'card-foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.15 0.01 260)',
    defaultDark: 'oklch(0.96 0.01 260)',
    description: 'Text color for content inside cards.',
    themePath: 'colors.cardForeground',
    tailwindNamespace: 'color',
  },
  {
    name: 'popover',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(1 0 0)',
    defaultDark: 'oklch(0.17 0.02 260)',
    description: 'Background for floating surfaces (popovers, dropdowns, tooltips).',
    themePath: 'colors.popover',
    tailwindNamespace: 'color',
  },
  {
    name: 'popover-foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.15 0.01 260)',
    defaultDark: 'oklch(0.96 0.01 260)',
    description: 'Text color for content inside popovers.',
    themePath: 'colors.popoverForeground',
    tailwindNamespace: 'color',
  },
  {
    name: 'primary',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.55 0.18 265)',
    defaultDark: 'oklch(0.7 0.16 265)',
    description: 'Brand primary. Used for filled buttons, focus ring, links.',
    themePath: 'colors.primary',
    tailwindNamespace: 'color',
  },
  {
    name: 'primary-foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.99 0 0)',
    defaultDark: 'oklch(0.14 0.02 260)',
    description: 'Text color that reads on `primary` backgrounds.',
    themePath: 'colors.primaryForeground',
    tailwindNamespace: 'color',
  },
  {
    name: 'secondary',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.94 0.005 260)',
    defaultDark: 'oklch(0.22 0.02 260)',
    description: 'Secondary surfaces and quiet button fills.',
    themePath: 'colors.secondary',
    tailwindNamespace: 'color',
  },
  {
    name: 'secondary-foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.15 0.01 260)',
    defaultDark: 'oklch(0.96 0.01 260)',
    description: 'Text color paired with `secondary`.',
    themePath: 'colors.secondaryForeground',
    tailwindNamespace: 'color',
  },
  {
    name: 'muted',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.95 0.005 260)',
    defaultDark: 'oklch(0.2 0.02 260)',
    description: 'Subdued surface for placeholder content and inactive rails.',
    themePath: 'colors.muted',
    tailwindNamespace: 'color',
  },
  {
    name: 'muted-foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.5 0.01 260)',
    defaultDark: 'oklch(0.65 0.02 260)',
    description: 'De-emphasized text (helper copy, captions, placeholders).',
    themePath: 'colors.mutedForeground',
    tailwindNamespace: 'color',
  },
  {
    name: 'accent',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.92 0.01 260)',
    defaultDark: 'oklch(0.25 0.02 260)',
    description: 'Hover/highlight surface for interactive items in menus and lists.',
    themePath: 'colors.accent',
    tailwindNamespace: 'color',
  },
  {
    name: 'accent-foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.15 0.01 260)',
    defaultDark: 'oklch(0.96 0.01 260)',
    description: 'Text color paired with `accent`.',
    themePath: 'colors.accentForeground',
    tailwindNamespace: 'color',
  },
  {
    name: 'border',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.9 0.01 260)',
    defaultDark: 'oklch(0.25 0.02 260)',
    description: 'Default border color across the system.',
    themePath: 'colors.border',
    tailwindNamespace: 'color',
  },
  {
    name: 'input',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.9 0.01 260)',
    defaultDark: 'oklch(0.25 0.02 260)',
    description: 'Border color for input controls (input, select, textarea).',
    themePath: 'colors.input',
    tailwindNamespace: 'color',
  },
  {
    name: 'ring',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.55 0.18 265)',
    defaultDark: 'oklch(0.7 0.16 265)',
    description: 'Focus ring color. Defaults to `primary`.',
    themePath: 'colors.ring',
    tailwindNamespace: 'color',
  },

  // Feedback
  {
    name: 'success',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.55 0.16 145)',
    defaultDark: 'oklch(0.72 0.15 145)',
    description: 'Positive feedback (success toasts, confirmation states).',
    themePath: 'colors.success',
    tailwindNamespace: 'color',
  },
  {
    name: 'success-foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.99 0 0)',
    defaultDark: 'oklch(0.14 0.02 260)',
    description: 'Text color paired with `success`.',
    themePath: 'colors.successForeground',
    tailwindNamespace: 'color',
  },
  {
    name: 'warning',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.65 0.14 85)',
    defaultDark: 'oklch(0.8 0.15 85)',
    description: 'Cautionary feedback (warning banners, caution states).',
    themePath: 'colors.warning',
    tailwindNamespace: 'color',
  },
  {
    name: 'warning-foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.15 0.01 260)',
    defaultDark: 'oklch(0.14 0.02 260)',
    description: 'Text color paired with `warning`.',
    themePath: 'colors.warningForeground',
    tailwindNamespace: 'color',
  },
  {
    name: 'info',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.5 0.18 230)',
    defaultDark: 'oklch(0.72 0.12 230)',
    description: 'Informational feedback (tips, notes, neutral accents).',
    themePath: 'colors.info',
    tailwindNamespace: 'color',
  },
  {
    name: 'info-foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.99 0 0)',
    defaultDark: 'oklch(0.14 0.02 260)',
    description: 'Text color paired with `info`.',
    themePath: 'colors.infoForeground',
    tailwindNamespace: 'color',
  },
  {
    name: 'destructive',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.55 0.22 25)',
    defaultDark: 'oklch(0.65 0.2 25)',
    description: 'Destructive actions (delete buttons, error states).',
    themePath: 'colors.destructive',
    tailwindNamespace: 'color',
  },
  {
    name: 'destructive-foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.99 0 0)',
    defaultDark: 'oklch(0.96 0.01 260)',
    description: 'Text color paired with `destructive`.',
    themePath: 'colors.destructiveForeground',
    tailwindNamespace: 'color',
  },
];

// ─────────────────────────────────────────────────────────────
// Layer 1 — Geometry, elevation, motion, typography roles
// Derived from scalars. Mostly stable across themes.
// ─────────────────────────────────────────────────────────────
const SEMANTIC_ROLES: readonly TokenSpec[] = [
  // Semantic radii — derived from --radius
  {
    name: 'radius-tight',
    layer: 'role',
    category: 'geometry',
    defaultLight: 'max(0rem, calc(var(--radius) - 0.625rem))',
    description: 'Tight radius for tag dots and micro shapes.',
    tailwindNamespace: 'radius',
    utilityAlias: 'tight',
  },
  {
    name: 'radius-pill',
    layer: 'role',
    category: 'geometry',
    defaultLight: 'max(0rem, calc(var(--radius) - 0.375rem))',
    description: 'Pill radius for chips, tags, and badges.',
    tailwindNamespace: 'radius',
    utilityAlias: 'pill',
  },
  {
    name: 'radius-control',
    layer: 'role',
    category: 'geometry',
    defaultLight: 'max(0rem, calc(var(--radius) - 0.25rem))',
    description: 'Radius for buttons, inputs, switches and other controls.',
    tailwindNamespace: 'radius',
    utilityAlias: 'control',
  },
  {
    name: 'radius-container',
    layer: 'role',
    category: 'geometry',
    defaultLight: 'var(--radius)',
    description: 'Radius for cards, panels, sidebars.',
    tailwindNamespace: 'radius',
    utilityAlias: 'container',
  },
  {
    name: 'radius-surface',
    layer: 'role',
    category: 'geometry',
    defaultLight: 'calc(var(--radius) + 0.25rem)',
    description: 'Radius for dialogs, sheets, popovers — surfaces that float.',
    tailwindNamespace: 'radius',
    utilityAlias: 'surface',
  },

  // Semantic shadows — alias the numeric scale.
  {
    name: 'shadow-surface',
    layer: 'role',
    category: 'elevation',
    defaultLight: 'var(--shadow-xs)',
    description: 'Subtle resting elevation (inline cards, quiet chrome).',
    tailwindNamespace: 'shadow',
    utilityAlias: 'surface',
  },
  {
    name: 'shadow-raised',
    layer: 'role',
    category: 'elevation',
    defaultLight: 'var(--shadow-sm)',
    description: 'Cards and buttons at rest or hover.',
    tailwindNamespace: 'shadow',
    utilityAlias: 'raised',
  },
  {
    name: 'shadow-overlay',
    layer: 'role',
    category: 'elevation',
    defaultLight: 'var(--shadow-md)',
    description: 'Popovers, dropdowns, tooltips — anything floating.',
    tailwindNamespace: 'shadow',
    utilityAlias: 'overlay',
  },
  {
    name: 'shadow-modal',
    layer: 'role',
    category: 'elevation',
    defaultLight: 'var(--shadow-lg)',
    description: 'Dialogs and sheets that command focus.',
    tailwindNamespace: 'shadow',
    utilityAlias: 'modal',
  },
  {
    name: 'shadow-spotlight',
    layer: 'role',
    category: 'elevation',
    defaultLight: 'var(--shadow-xl)',
    description: 'Toasts and command palettes — most-elevated transient surfaces.',
    tailwindNamespace: 'shadow',
    utilityAlias: 'spotlight',
  },

  // Motion channels
  {
    name: 'motion-instant-duration',
    layer: 'role',
    category: 'motion',
    defaultLight: 'max(80ms, calc(var(--motion-duration, 220ms) * 0.45))',
    description: 'Fastest channel — hover, focus, instant feedback.',
    tailwindNamespace: 'motion',
    utilityAlias: 'instant',
  },
  {
    name: 'motion-standard-duration',
    layer: 'role',
    category: 'motion',
    defaultLight: 'var(--motion-duration, 220ms)',
    description: 'Default transition channel for most state changes.',
    tailwindNamespace: 'motion',
    utilityAlias: 'standard',
  },
  {
    name: 'motion-considered-duration',
    layer: 'role',
    category: 'motion',
    defaultLight: 'calc(var(--motion-duration, 220ms) * 1.8)',
    description: 'Emphasized reveals — sheets, accordions, accordions.',
    tailwindNamespace: 'motion',
    utilityAlias: 'considered',
  },
  {
    name: 'motion-instant-easing',
    layer: 'role',
    category: 'motion',
    defaultLight: 'var(--motion-easing, cubic-bezier(0.16, 1, 0.3, 1))',
    description: 'Easing for the instant motion channel.',
  },
  {
    name: 'motion-standard-easing',
    layer: 'role',
    category: 'motion',
    defaultLight: 'var(--motion-easing, cubic-bezier(0.16, 1, 0.3, 1))',
    description: 'Easing for the standard motion channel.',
  },
  {
    name: 'motion-considered-easing',
    layer: 'role',
    category: 'motion',
    defaultLight: 'var(--motion-easing, cubic-bezier(0.16, 1, 0.3, 1))',
    description: 'Easing for the considered motion channel.',
  },

  // State-layer opacities
  {
    name: 'state-hover-opacity',
    layer: 'role',
    category: 'state',
    defaultLight: '0.08',
    description: 'Overlay opacity for hover state layers.',
    themePath: 'state.hoverOpacity',
    tailwindNamespace: 'opacity',
    utilityAlias: 'state-hover',
  },
  {
    name: 'state-focus-opacity',
    layer: 'role',
    category: 'state',
    defaultLight: '0.12',
    description: 'Overlay opacity for focus state layers.',
    themePath: 'state.focusOpacity',
    tailwindNamespace: 'opacity',
    utilityAlias: 'state-focus',
  },
  {
    name: 'state-pressed-opacity',
    layer: 'role',
    category: 'state',
    defaultLight: '0.16',
    description: 'Overlay opacity for pressed state layers.',
    themePath: 'state.pressedOpacity',
    tailwindNamespace: 'opacity',
    utilityAlias: 'state-pressed',
  },
  {
    name: 'state-selected-opacity',
    layer: 'role',
    category: 'state',
    defaultLight: '0.12',
    description: 'Overlay opacity for selected state layers.',
    themePath: 'state.selectedOpacity',
    tailwindNamespace: 'opacity',
    utilityAlias: 'state-selected',
  },
  {
    name: 'state-disabled-opacity',
    layer: 'role',
    category: 'state',
    defaultLight: '0.38',
    description: 'Opacity applied to disabled controls.',
    themePath: 'state.disabledOpacity',
    tailwindNamespace: 'opacity',
    utilityAlias: 'state-disabled',
  },
];

// ─────────────────────────────────────────────────────────────
// Layer 2 — Per-component overrides (existing surface)
// Step 1 covers the tokens that already exist in clay.css. Step 4
// expands these to border / typography / focus / motion / state for
// every component.
//
// `defaultLight` for component tokens is the fallback expression that
// resolves to a Layer 1 role when the theme leaves the override blank.
// ─────────────────────────────────────────────────────────────
const COMPONENT_TOKENS: readonly TokenSpec[] = [
  // Button
  {
    name: 'button-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'button',
    defaultLight: 'var(--radius-control)',
    description: 'Button corner radius. Falls back to `radius-control`.',
    themePath: 'components.button.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'button',
  },
  {
    name: 'button-shadow',
    layer: 'component',
    category: 'elevation',
    appliesTo: 'button',
    defaultLight: 'var(--shadow-surface)',
    description: 'Resting elevation under a button.',
    themePath: 'components.button.shadow',
    tailwindNamespace: 'shadow',
    utilityAlias: 'button',
  },
  {
    name: 'button-corner-shape',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'button',
    defaultLight: 'var(--corner-shape, round)',
    description: 'Corner geometry (round / bevel / squircle / scoop / notch).',
    themePath: 'components.button.cornerShape',
  },
  {
    name: 'button-filled-container',
    layer: 'component',
    category: 'color',
    appliesTo: 'button',
    defaultLight: 'var(--primary)',
    description: 'Background of the filled button variant.',
    themePath: 'components.button.filledContainer',
    tailwindNamespace: 'color',
  },
  {
    name: 'button-filled-label',
    layer: 'component',
    category: 'color',
    appliesTo: 'button',
    defaultLight: 'var(--primary-foreground)',
    description: 'Label color of the filled button variant.',
    themePath: 'components.button.filledLabel',
    tailwindNamespace: 'color',
  },
  {
    name: 'button-outline-border',
    layer: 'component',
    category: 'color',
    appliesTo: 'button',
    defaultLight: 'var(--border)',
    description: 'Border color of the outline button variant.',
    themePath: 'components.button.outlineBorder',
    tailwindNamespace: 'color',
  },
  {
    name: 'button-outline-label',
    layer: 'component',
    category: 'color',
    appliesTo: 'button',
    defaultLight: 'var(--foreground)',
    description: 'Label color of the outline button variant.',
    themePath: 'components.button.outlineLabel',
    tailwindNamespace: 'color',
  },

  // Card
  {
    name: 'card-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'card',
    defaultLight: 'var(--radius-container)',
    description: 'Card corner radius.',
    themePath: 'components.card.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'card',
  },
  {
    name: 'card-shadow',
    layer: 'component',
    category: 'elevation',
    appliesTo: 'card',
    defaultLight: 'var(--shadow-raised)',
    description: 'Card elevation.',
    themePath: 'components.card.shadow',
    tailwindNamespace: 'shadow',
    utilityAlias: 'card',
  },
  {
    name: 'card-corner-shape',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'card',
    defaultLight: 'var(--corner-shape, round)',
    description: 'Card corner geometry.',
    themePath: 'components.card.cornerShape',
  },
  {
    name: 'card-container',
    layer: 'component',
    category: 'color',
    appliesTo: 'card',
    defaultLight: 'var(--card)',
    description: 'Card background.',
    themePath: 'components.card.container',
    tailwindNamespace: 'color',
  },
  {
    name: 'card-label',
    layer: 'component',
    category: 'color',
    appliesTo: 'card',
    defaultLight: 'var(--card-foreground)',
    description: 'Card text color.',
    themePath: 'components.card.label',
    tailwindNamespace: 'color',
  },

  // Dialog
  {
    name: 'dialog-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'dialog',
    defaultLight: 'var(--radius-surface)',
    description: 'Dialog corner radius.',
    themePath: 'components.dialog.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'dialog',
  },
  {
    name: 'dialog-shadow',
    layer: 'component',
    category: 'elevation',
    appliesTo: 'dialog',
    defaultLight: 'var(--shadow-modal)',
    description: 'Dialog elevation.',
    themePath: 'components.dialog.shadow',
    tailwindNamespace: 'shadow',
    utilityAlias: 'dialog',
  },
  {
    name: 'dialog-corner-shape',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'dialog',
    defaultLight: 'var(--corner-shape, round)',
    description: 'Dialog corner geometry.',
    themePath: 'components.dialog.cornerShape',
  },
  {
    name: 'dialog-container',
    layer: 'component',
    category: 'color',
    appliesTo: 'dialog',
    defaultLight: 'var(--popover)',
    description: 'Dialog background.',
    themePath: 'components.dialog.container',
    tailwindNamespace: 'color',
  },
  {
    name: 'dialog-label',
    layer: 'component',
    category: 'color',
    appliesTo: 'dialog',
    defaultLight: 'var(--popover-foreground)',
    description: 'Dialog text color.',
    themePath: 'components.dialog.label',
    tailwindNamespace: 'color',
  },

  // Popover
  {
    name: 'popover-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'popover',
    defaultLight: 'var(--radius-surface)',
    description: 'Popover corner radius.',
    themePath: 'components.popover.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'popover',
  },
  {
    name: 'popover-shadow',
    layer: 'component',
    category: 'elevation',
    appliesTo: 'popover',
    defaultLight: 'var(--shadow-overlay)',
    description: 'Popover elevation.',
    themePath: 'components.popover.shadow',
    tailwindNamespace: 'shadow',
    utilityAlias: 'popover',
  },
  {
    name: 'popover-corner-shape',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'popover',
    defaultLight: 'var(--corner-shape, round)',
    description: 'Popover corner geometry.',
    themePath: 'components.popover.cornerShape',
  },

  // Tooltip
  {
    name: 'tooltip-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'tooltip',
    defaultLight: 'var(--radius-control)',
    description: 'Tooltip corner radius.',
    themePath: 'components.tooltip.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'tooltip',
  },
  {
    name: 'tooltip-shadow',
    layer: 'component',
    category: 'elevation',
    appliesTo: 'tooltip',
    defaultLight: 'var(--shadow-overlay)',
    description: 'Tooltip elevation.',
    themePath: 'components.tooltip.shadow',
    tailwindNamespace: 'shadow',
    utilityAlias: 'tooltip',
  },
  {
    name: 'tooltip-corner-shape',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'tooltip',
    defaultLight: 'var(--corner-shape, round)',
    description: 'Tooltip corner geometry.',
    themePath: 'components.tooltip.cornerShape',
  },

  // Input — covers Input, Textarea, Select trigger, PasswordInput
  {
    name: 'input-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'input',
    defaultLight: 'var(--radius-control)',
    description: 'Input corner radius.',
    themePath: 'components.input.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'input',
  },
  {
    name: 'input-corner-shape',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'input',
    defaultLight: 'var(--corner-shape, round)',
    description: 'Input corner geometry.',
    themePath: 'components.input.cornerShape',
  },
  {
    name: 'input-container',
    layer: 'component',
    category: 'color',
    appliesTo: 'input',
    defaultLight: 'var(--background)',
    description: 'Input background.',
    themePath: 'components.input.container',
    tailwindNamespace: 'color',
  },
  {
    name: 'input-label',
    layer: 'component',
    category: 'color',
    appliesTo: 'input',
    defaultLight: 'var(--foreground)',
    description: 'Input text color.',
    themePath: 'components.input.label',
    tailwindNamespace: 'color',
  },
  {
    name: 'input-border',
    layer: 'component',
    category: 'color',
    appliesTo: 'input',
    defaultLight: 'var(--input)',
    description: 'Input border color.',
    themePath: 'components.input.border',
    tailwindNamespace: 'color',
  },
  {
    name: 'input-placeholder',
    layer: 'component',
    category: 'color',
    appliesTo: 'input',
    defaultLight: 'var(--muted-foreground)',
    description: 'Input placeholder text color.',
    themePath: 'components.input.placeholder',
    tailwindNamespace: 'color',
  },

  // Select
  {
    name: 'select-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'select',
    defaultLight: 'var(--radius-control)',
    description: 'Select trigger corner radius.',
    themePath: 'components.select.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'select',
  },
  {
    name: 'select-corner-shape',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'select',
    defaultLight: 'var(--corner-shape, round)',
    description: 'Select corner geometry.',
    themePath: 'components.select.cornerShape',
  },

  // Menu (dropdown-menu, context-menu surfaces)
  {
    name: 'menu-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'menu',
    defaultLight: 'var(--radius-surface)',
    description: 'Menu surface corner radius.',
    themePath: 'components.menu.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'menu',
  },
  {
    name: 'menu-shadow',
    layer: 'component',
    category: 'elevation',
    appliesTo: 'menu',
    defaultLight: 'var(--shadow-overlay)',
    description: 'Menu surface elevation.',
    themePath: 'components.menu.shadow',
    tailwindNamespace: 'shadow',
    utilityAlias: 'menu',
  },
  {
    name: 'menu-corner-shape',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'menu',
    defaultLight: 'var(--corner-shape, round)',
    description: 'Menu surface corner geometry.',
    themePath: 'components.menu.cornerShape',
  },
  {
    name: 'menu-item-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'menu-item',
    defaultLight: 'var(--radius-control)',
    description: 'Menu-item corner radius.',
    themePath: 'components.menuItem.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'menu-item',
  },
  {
    name: 'menu-item-corner-shape',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'menu-item',
    defaultLight: 'var(--corner-shape, round)',
    description: 'Menu-item corner geometry.',
    themePath: 'components.menuItem.cornerShape',
  },

  // Checkbox
  {
    name: 'checkbox-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'checkbox',
    defaultLight: 'var(--radius-tight)',
    description: 'Checkbox corner radius.',
    themePath: 'components.checkbox.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'checkbox',
  },
  {
    name: 'checkbox-corner-shape',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'checkbox',
    defaultLight: 'var(--corner-shape, round)',
    description: 'Checkbox corner geometry.',
    themePath: 'components.checkbox.cornerShape',
  },

  // Badge
  {
    name: 'badge-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'badge',
    defaultLight: 'var(--radius-pill)',
    description: 'Badge corner radius.',
    themePath: 'components.badge.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'badge',
  },
  {
    name: 'badge-corner-shape',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'badge',
    defaultLight: 'var(--corner-shape, round)',
    description: 'Badge corner geometry.',
    themePath: 'components.badge.cornerShape',
  },

  // Tabs
  {
    name: 'tabs-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'tabs',
    defaultLight: 'var(--radius-control)',
    description: 'Tabs corner radius.',
    themePath: 'components.tabs.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'tabs',
  },
  {
    name: 'tabs-corner-shape',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'tabs',
    defaultLight: 'var(--corner-shape, round)',
    description: 'Tabs corner geometry.',
    themePath: 'components.tabs.cornerShape',
  },

  // Alert
  {
    name: 'alert-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'alert',
    defaultLight: 'var(--radius-container)',
    description: 'Alert corner radius.',
    themePath: 'components.alert.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'alert',
  },
  {
    name: 'alert-corner-shape',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'alert',
    defaultLight: 'var(--corner-shape, round)',
    description: 'Alert corner geometry.',
    themePath: 'components.alert.cornerShape',
  },

  // Toast
  {
    name: 'toast-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'toast',
    defaultLight: 'var(--radius-container)',
    description: 'Toast corner radius.',
    themePath: 'components.toast.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'toast',
  },
  {
    name: 'toast-shadow',
    layer: 'component',
    category: 'elevation',
    appliesTo: 'toast',
    defaultLight: 'var(--shadow-spotlight)',
    description: 'Toast elevation.',
    themePath: 'components.toast.shadow',
    tailwindNamespace: 'shadow',
    utilityAlias: 'toast',
  },
  {
    name: 'toast-corner-shape',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'toast',
    defaultLight: 'var(--corner-shape, round)',
    description: 'Toast corner geometry.',
    themePath: 'components.toast.cornerShape',
  },

  // Avatar
  {
    name: 'avatar-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'avatar',
    defaultLight: '9999px',
    description: 'Avatar corner radius. Default is fully circular.',
    themePath: 'components.avatar.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'avatar',
  },
  {
    name: 'avatar-corner-shape',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'avatar',
    defaultLight: 'var(--corner-shape, round)',
    description: 'Avatar corner geometry.',
    themePath: 'components.avatar.cornerShape',
  },

  // Switch
  {
    name: 'switch-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'switch',
    defaultLight: '9999px',
    description: 'Switch track corner radius. Default is fully rounded.',
    themePath: 'components.switch.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'switch',
  },
  {
    name: 'switch-corner-shape',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'switch',
    defaultLight: 'var(--corner-shape, round)',
    description: 'Switch track corner geometry.',
    themePath: 'components.switch.cornerShape',
  },
  {
    name: 'switch-thumb-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'switch-thumb',
    defaultLight: '9999px',
    description: 'Switch thumb corner radius.',
    themePath: 'components.switchThumb.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'switch-thumb',
  },
  {
    name: 'switch-thumb-corner-shape',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'switch-thumb',
    defaultLight: 'var(--corner-shape, round)',
    description: 'Switch thumb corner geometry.',
    themePath: 'components.switchThumb.cornerShape',
  },

  // Icon — three foreground levels
  {
    name: 'icon',
    layer: 'component',
    category: 'color',
    appliesTo: 'icon',
    defaultLight: 'var(--foreground)',
    description: 'Default icon color.',
    themePath: 'components.icon.default',
    tailwindNamespace: 'color',
  },
  {
    name: 'icon-muted',
    layer: 'component',
    category: 'color',
    appliesTo: 'icon',
    defaultLight: 'var(--muted-foreground)',
    description: 'Muted icon color.',
    themePath: 'components.icon.muted',
    tailwindNamespace: 'color',
  },
  {
    name: 'icon-primary',
    layer: 'component',
    category: 'color',
    appliesTo: 'icon',
    defaultLight: 'var(--primary)',
    description: 'Primary icon color (interactive accents).',
    themePath: 'components.icon.primary',
    tailwindNamespace: 'color',
  },
];

// ─────────────────────────────────────────────────────────────
// Layer 2 — Per-component expansion
// Generated through the helpers in `./expand.ts` so each component's
// surface stays consistent. Hand-curated geometry defaults reflect the
// existing Tailwind class numbers (h-9 = 2.25rem, px-4 = 1rem, etc.).
// ─────────────────────────────────────────────────────────────

const SPACING_1 = 'calc(var(--spacing) * 1)';
const SPACING_1_5 = 'calc(var(--spacing) * 1.5)';
const SPACING_2 = 'calc(var(--spacing) * 2)';
const SPACING_3 = 'calc(var(--spacing) * 3)';
const SPACING_4 = 'calc(var(--spacing) * 4)';
const SPACING_6 = 'calc(var(--spacing) * 6)';

const COMPONENT_EXPANSIONS: readonly TokenSpec[] = [
  // Button — full interactive control surface
  ...controlSurfaceTokens(
    meta('button'),
    { height: '2.25rem', paddingX: SPACING_4, paddingY: SPACING_2, gap: SPACING_2 },
    { fontWeight: '500', fontSize: 'var(--text-body-md)' }
  ),

  // Input / Textarea / PasswordInput — always-bordered (1px) by default.
  ...controlSurfaceTokens(
    meta('input'),
    { height: '2.25rem', paddingX: SPACING_3, paddingY: SPACING_2, gap: SPACING_2 },
    { fontSize: 'var(--text-body-md)' },
    '1px'
  ),
  ...controlSurfaceTokens(
    meta('textarea'),
    { paddingX: SPACING_3, paddingY: SPACING_2, gap: SPACING_2 },
    { fontSize: 'var(--text-body-md)' },
    '1px'
  ),
  {
    name: 'textarea-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'textarea',
    defaultLight: 'var(--radius-control)',
    description: 'Textarea corner radius.',
    themePath: 'components.textarea.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'textarea',
  },
  ...controlSurfaceTokens(
    meta('password-input', 'passwordInput'),
    { height: '2.25rem', paddingX: SPACING_3, paddingY: SPACING_2 },
    {},
    '1px'
  ),

  // Select trigger — always-bordered.
  ...controlSurfaceTokens(
    meta('select'),
    { height: '2.25rem', paddingX: SPACING_3, paddingY: SPACING_2, gap: SPACING_2 },
    {},
    '1px'
  ),

  // Card — surface, no padding height (those are layout-driven)
  ...borderTokens(meta('card'), '1px'),
  ...motionTokens(meta('card')),
  ...typographyTokens(meta('card'), { fontSize: 'var(--text-body-md)' }),
  ...geometryTokens(meta('card'), { paddingX: SPACING_6, paddingY: SPACING_6, gap: SPACING_4 }),
  {
    name: 'card-backdrop-blur',
    layer: 'component',
    category: 'elevation',
    appliesTo: 'card',
    defaultLight: '0px',
    description: 'Backdrop blur applied behind a translucent card. Set non-zero for glass.',
    themePath: 'components.card.backdropBlur',
  },

  // Dialog — overlay surface
  ...borderTokens(meta('dialog'), '1px'),
  ...focusTokens(meta('dialog')),
  ...motionTokens(meta('dialog')),
  ...geometryTokens(meta('dialog'), { paddingX: SPACING_6, paddingY: SPACING_6, gap: SPACING_4 }),
  {
    name: 'dialog-backdrop-blur',
    layer: 'component',
    category: 'elevation',
    appliesTo: 'dialog',
    defaultLight: '0px',
    description: 'Backdrop blur applied behind a translucent dialog.',
    themePath: 'components.dialog.backdropBlur',
  },

  // Sheet — slide-in surface
  {
    name: 'sheet-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'sheet',
    defaultLight: 'var(--radius-surface)',
    description: 'Sheet corner radius.',
    themePath: 'components.sheet.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'sheet',
  },
  {
    name: 'sheet-shadow',
    layer: 'component',
    category: 'elevation',
    appliesTo: 'sheet',
    defaultLight: 'var(--shadow-modal)',
    description: 'Sheet elevation.',
    themePath: 'components.sheet.shadow',
    tailwindNamespace: 'shadow',
    utilityAlias: 'sheet',
  },
  ...borderTokens(meta('sheet'), '1px'),
  ...motionTokens(meta('sheet')),
  ...geometryTokens(meta('sheet'), { paddingX: SPACING_6, paddingY: SPACING_6, gap: SPACING_4 }),
  {
    name: 'sheet-backdrop-blur',
    layer: 'component',
    category: 'elevation',
    appliesTo: 'sheet',
    defaultLight: '0px',
    description: 'Backdrop blur applied behind a translucent sheet.',
    themePath: 'components.sheet.backdropBlur',
  },

  // Popover — overlay surface
  ...borderTokens(meta('popover'), '1px'),
  ...motionTokens(meta('popover')),
  ...geometryTokens(meta('popover'), { paddingX: SPACING_3, paddingY: SPACING_3, gap: SPACING_2 }),
  {
    name: 'popover-backdrop-blur',
    layer: 'component',
    category: 'elevation',
    appliesTo: 'popover',
    defaultLight: '0px',
    description: 'Backdrop blur applied behind a translucent popover.',
    themePath: 'components.popover.backdropBlur',
  },

  // Tooltip — overlay surface
  ...borderTokens(meta('tooltip')),
  ...motionTokens(meta('tooltip')),
  ...typographyTokens(meta('tooltip'), { fontSize: 'var(--text-label-md)', fontWeight: '500' }),
  ...geometryTokens(meta('tooltip'), { paddingX: SPACING_2, paddingY: SPACING_1 }),

  // Menu (dropdown surface)
  ...borderTokens(meta('menu'), '1px'),
  ...motionTokens(meta('menu')),
  ...geometryTokens(meta('menu'), { paddingX: SPACING_1, paddingY: SPACING_1, gap: '0.125rem' }),
  {
    name: 'menu-backdrop-blur',
    layer: 'component',
    category: 'elevation',
    appliesTo: 'menu',
    defaultLight: '0px',
    description: 'Backdrop blur applied behind a translucent dropdown menu.',
    themePath: 'components.menu.backdropBlur',
  },

  // Menu item
  ...controlSurfaceTokens(
    meta('menu-item', 'menuItem'),
    { paddingX: SPACING_2, paddingY: SPACING_1_5, gap: SPACING_2 },
    { fontSize: 'var(--text-body-md)' }
  ),

  // Badge
  ...controlSurfaceTokens(
    meta('badge'),
    { height: '1.5rem', paddingX: SPACING_2, paddingY: '0.125rem', gap: SPACING_1 },
    { fontSize: 'var(--text-label-md)', fontWeight: '500' }
  ),

  // Tabs
  ...borderTokens(meta('tabs'), '1px'),
  ...motionTokens(meta('tabs')),
  ...geometryTokens(meta('tabs'), { gap: SPACING_1 }),
  {
    name: 'tabs-trigger-padding-x',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'tabs',
    defaultLight: SPACING_3,
    description: 'Inline padding inside a tab trigger.',
    themePath: 'components.tabs.triggerPaddingX',
  },
  {
    name: 'tabs-trigger-padding-y',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'tabs',
    defaultLight: SPACING_1_5,
    description: 'Block padding inside a tab trigger.',
    themePath: 'components.tabs.triggerPaddingY',
  },
  ...focusTokens(meta('tabs')),
  ...typographyTokens(meta('tabs'), { fontSize: 'var(--text-body-md)' }),

  // Switch
  ...borderTokens(meta('switch'), '1px'),
  ...focusTokens(meta('switch')),
  ...motionTokens(meta('switch')),
  ...stateTokens(meta('switch')),
  // Track sizing leaves room for the thumb plus the 1px transparent border
  // that holds layout when focus draws a coloured border. Track width fits
  // 2× the thumb (one parked, one full travel) plus padding.
  {
    name: 'switch-track-width',
    layer: 'component',
    category: 'geometry',
    type: 'size',
    appliesTo: 'switch',
    defaultLight: '2.5rem',
    description: 'Switch track width. Fits two thumb diameters + padding + border.',
    themePath: 'components.switch.trackWidth',
  },
  {
    name: 'switch-track-height',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'switch',
    defaultLight: '1.5rem',
    description: 'Switch track height. Leaves room for thumb + padding + border.',
    themePath: 'components.switch.trackHeight',
  },
  {
    name: 'switch-thumb-size',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'switch-thumb',
    defaultLight: '1rem',
    description: 'Switch thumb diameter at the default size.',
    themePath: 'components.switchThumb.size',
  },

  // Checkbox
  ...borderTokens(meta('checkbox'), '1px'),
  ...focusTokens(meta('checkbox')),
  ...motionTokens(meta('checkbox')),
  {
    name: 'checkbox-size',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'checkbox',
    defaultLight: '1rem',
    description: 'Checkbox box edge length.',
    themePath: 'components.checkbox.size',
  },

  // Slider
  ...focusTokens(meta('slider')),
  ...motionTokens(meta('slider')),
  {
    name: 'slider-track-height',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'slider',
    defaultLight: '0.25rem',
    description: 'Slider track thickness.',
    themePath: 'components.slider.trackHeight',
  },
  {
    name: 'slider-thumb-size',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'slider',
    defaultLight: '1rem',
    description: 'Slider thumb diameter.',
    themePath: 'components.slider.thumbSize',
  },
  {
    name: 'slider-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'slider',
    defaultLight: '9999px',
    description: 'Track corner radius. Set lower for square / brutalist looks.',
    themePath: 'components.slider.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'slider',
  },
  {
    name: 'slider-thumb-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'slider',
    defaultLight: '9999px',
    description: 'Thumb corner radius. Lower for square thumbs.',
    themePath: 'components.slider.thumbRadius',
    tailwindNamespace: 'radius',
    utilityAlias: 'slider-thumb',
  },
  {
    name: 'slider-tick-size',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'slider',
    defaultLight: '0.25rem',
    description: 'Tick dot diameter on the track.',
    themePath: 'components.slider.tickSize',
  },
  {
    name: 'slider-thumb-border-width',
    layer: 'component',
    category: 'border',
    appliesTo: 'slider',
    defaultLight: '2px',
    description: 'Thumb border width — the contrast halo between the thumb and the track.',
    themePath: 'components.slider.thumbBorderWidth',
  },
  {
    name: 'slider-thumb-shadow',
    layer: 'component',
    category: 'elevation',
    appliesTo: 'slider',
    defaultLight: 'var(--shadow-raised)',
    description: 'Thumb drop shadow. Falls back to the global `--shadow-raised`.',
    themePath: 'components.slider.thumbShadow',
    tailwindNamespace: 'shadow',
    utilityAlias: 'slider-thumb',
  },
  {
    name: 'slider-track',
    layer: 'component',
    category: 'color',
    appliesTo: 'slider',
    defaultLight: 'var(--muted)',
    description: 'Unfilled portion of the track.',
    themePath: 'components.slider.track',
    tailwindNamespace: 'color',
  },
  {
    name: 'slider-fill',
    layer: 'component',
    category: 'color',
    appliesTo: 'slider',
    defaultLight: 'var(--primary)',
    description: 'Filled portion of the track (left of the thumb).',
    themePath: 'components.slider.fill',
    tailwindNamespace: 'color',
  },
  {
    name: 'slider-thumb',
    layer: 'component',
    category: 'color',
    appliesTo: 'slider',
    defaultLight: 'var(--primary)',
    description: 'Thumb fill color.',
    themePath: 'components.slider.thumb',
    tailwindNamespace: 'color',
  },
  {
    name: 'slider-thumb-border',
    layer: 'component',
    category: 'color',
    appliesTo: 'slider',
    defaultLight: 'var(--background)',
    description: 'Thumb border (the halo separating thumb from track).',
    themePath: 'components.slider.thumbBorder',
    tailwindNamespace: 'color',
  },
  {
    name: 'slider-tick',
    layer: 'component',
    category: 'color',
    appliesTo: 'slider',
    defaultLight: 'var(--foreground)',
    description: 'Inactive tick dot color (over the unfilled track). Used with reduced opacity.',
    themePath: 'components.slider.tick',
    tailwindNamespace: 'color',
  },
  {
    name: 'slider-tick-active',
    layer: 'component',
    category: 'color',
    appliesTo: 'slider',
    defaultLight: 'var(--primary-foreground)',
    description: 'Active tick dot color (over the filled track). Used with reduced opacity.',
    themePath: 'components.slider.tickActive',
    tailwindNamespace: 'color',
  },
  {
    name: 'slider-label',
    layer: 'component',
    category: 'color',
    appliesTo: 'slider',
    defaultLight: 'var(--muted-foreground)',
    description: 'Tick label text color.',
    themePath: 'components.slider.label',
    tailwindNamespace: 'color',
  },
  {
    name: 'slider-label-active',
    layer: 'component',
    category: 'color',
    appliesTo: 'slider',
    defaultLight: 'var(--foreground)',
    description: 'Tick label color when its value matches the current slider value.',
    themePath: 'components.slider.labelActive',
    tailwindNamespace: 'color',
  },

  // Avatar
  ...borderTokens(meta('avatar')),
  {
    name: 'avatar-size',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'avatar',
    defaultLight: '2rem',
    description: 'Avatar diameter at the default size.',
    themePath: 'components.avatar.size',
  },

  // Toast
  ...borderTokens(meta('toast'), '1px'),
  ...motionTokens(meta('toast')),
  ...geometryTokens(meta('toast'), { paddingX: SPACING_4, paddingY: SPACING_3, gap: SPACING_2 }),

  // Alert (alert-dialog inline alert)
  ...borderTokens(meta('alert'), '1px'),
  ...geometryTokens(meta('alert'), { paddingX: SPACING_4, paddingY: SPACING_3, gap: SPACING_2 }),

  // Sidebar
  ...borderTokens(meta('sidebar'), '1px'),
  ...geometryTokens(meta('sidebar'), { paddingX: SPACING_3, paddingY: SPACING_3, gap: SPACING_2 }),
  {
    name: 'sidebar-width',
    layer: 'component',
    category: 'geometry',
    type: 'size',
    appliesTo: 'sidebar',
    defaultLight: '16rem',
    description: 'Sidebar width when expanded.',
    themePath: 'components.sidebar.width',
  },
  {
    name: 'sidebar-width-icon',
    layer: 'component',
    category: 'geometry',
    type: 'size',
    appliesTo: 'sidebar',
    defaultLight: '3rem',
    description: 'Sidebar width when collapsed to icon-only mode.',
    themePath: 'components.sidebar.widthIcon',
  },
  {
    name: 'sidebar-width-mobile',
    layer: 'component',
    category: 'geometry',
    type: 'size',
    appliesTo: 'sidebar',
    defaultLight: '18rem',
    description: 'Sidebar width when shown as a mobile sheet.',
    themePath: 'components.sidebar.widthMobile',
  },

  // Separator
  {
    name: 'separator-color',
    layer: 'component',
    category: 'color',
    appliesTo: 'separator',
    defaultLight: 'var(--border)',
    description: 'Separator line color.',
    themePath: 'components.separator.color',
    tailwindNamespace: 'color',
  },
  {
    name: 'separator-width',
    layer: 'component',
    category: 'border',
    type: 'border-width',
    appliesTo: 'separator',
    defaultLight: '1px',
    description: 'Separator line thickness.',
    themePath: 'components.separator.width',
  },
  {
    name: 'separator-style',
    layer: 'component',
    category: 'border',
    appliesTo: 'separator',
    defaultLight: 'solid',
    description: 'Separator line style (`solid`, `dashed`, `double`).',
    themePath: 'components.separator.style',
  },

  // Progress
  {
    name: 'progress-track-color',
    layer: 'component',
    category: 'color',
    appliesTo: 'progress',
    defaultLight: 'var(--secondary)',
    description: 'Background of the progress track.',
    themePath: 'components.progress.trackColor',
    tailwindNamespace: 'color',
  },
  {
    name: 'progress-indicator-color',
    layer: 'component',
    category: 'color',
    appliesTo: 'progress',
    defaultLight: 'var(--primary)',
    description: 'Foreground of the progress indicator.',
    themePath: 'components.progress.indicatorColor',
    tailwindNamespace: 'color',
  },
  {
    name: 'progress-track-height',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'progress',
    defaultLight: '0.5rem',
    description: 'Progress track thickness.',
    themePath: 'components.progress.trackHeight',
  },

  // Tables
  {
    name: 'table-header-bg',
    layer: 'component',
    category: 'color',
    appliesTo: 'table',
    defaultLight: 'var(--muted)',
    description: 'Background for table header rows.',
    themePath: 'components.table.headerBg',
    tailwindNamespace: 'color',
  },
  {
    name: 'table-row-bg',
    layer: 'component',
    category: 'color',
    appliesTo: 'table',
    defaultLight: 'var(--background)',
    description: 'Background for table body rows.',
    themePath: 'components.table.rowBg',
    tailwindNamespace: 'color',
  },
  {
    name: 'table-row-hover-bg',
    layer: 'component',
    category: 'color',
    appliesTo: 'table',
    defaultLight: 'var(--accent)',
    description: 'Background for hovered table rows.',
    themePath: 'components.table.rowHoverBg',
    tailwindNamespace: 'color',
  },
  ...borderTokens(meta('table'), '1px'),
  ...geometryTokens(meta('table'), { paddingX: SPACING_3, paddingY: SPACING_2 }),

  // Code Block
  {
    name: 'code-block-bg',
    layer: 'component',
    category: 'color',
    appliesTo: 'code-block',
    defaultLight: 'var(--muted)',
    description: 'Code block background.',
    themePath: 'components.codeBlock.bg',
    tailwindNamespace: 'color',
  },
  {
    name: 'code-block-radius',
    layer: 'component',
    category: 'geometry',
    appliesTo: 'code-block',
    defaultLight: 'var(--radius-control)',
    description: 'Code block corner radius.',
    themePath: 'components.codeBlock.radius',
    tailwindNamespace: 'radius',
    utilityAlias: 'code-block',
  },
  ...borderTokens(meta('code-block', 'codeBlock'), '1px'),
  ...geometryTokens(meta('code-block', 'codeBlock'), { paddingX: SPACING_4, paddingY: SPACING_3 }),
  ...typographyTokens(meta('code-block', 'codeBlock'), {
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-body-sm)',
  }),

  // Label
  ...typographyTokens(meta('label'), {
    fontSize: 'var(--text-label-md)',
    fontWeight: '500',
  }),
];

const RAW_REGISTRY: readonly TokenSpec[] = [
  ...SCALARS,
  ...COLOR_ROLES,
  ...SEMANTIC_ROLES,
  ...COMPONENT_TOKENS,
  ...COMPONENT_EXPANSIONS,
];

/**
 * Full token registry. Every entry has its `type` filled in — either
 * explicitly authored or inferred from the name's suffix (see
 * `./infer.ts`). Downstream code can safely treat `type` as required.
 */
export const TOKEN_REGISTRY: readonly ResolvedTokenSpec[] = RAW_REGISTRY.map((token) => ({
  ...token,
  type: token.type ?? inferTokenType(token.name),
}));

/**
 * O(1) lookup by token name.
 */
export const TOKENS_BY_NAME: Readonly<Record<string, ResolvedTokenSpec>> = Object.fromEntries(
  TOKEN_REGISTRY.map((token) => [token.name, token])
);

/**
 * Filter tokens by their granular value type. Useful when generating
 * theme-editor UI that needs e.g. all radius tokens or all shadow tokens.
 */
export function tokensByType(type: ResolvedTokenSpec['type']): readonly ResolvedTokenSpec[] {
  return TOKEN_REGISTRY.filter((token) => token.type === type);
}
