/**
 * `brika docs`: generate BLOCKS.md, a reference of this plugin's workflow
 * blocks. Works offline from the package.json manifest (id, name, description,
 * category); when the local hub is running and has this plugin loaded, the
 * reference is enriched with each block's ports and resolved types.
 */

import { existsSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { defineCommand } from '@brika/cli';
import pc from 'picocolors';
import { hubOrigin, pingHub } from '../hub';

interface ManifestBlock {
  id: string;
  name?: string;
  description?: string;
  category?: string;
}

interface HubPort {
  id: string;
  name?: string;
}

interface HubBlock {
  id: string;
  pluginId?: string;
  inputs?: HubPort[];
  outputs?: HubPort[];
}

function asManifestBlocks(value: unknown): ManifestBlock[] {
  if (!Array.isArray(value)) {
    return [];
  }
  const blocks: ManifestBlock[] = [];
  for (const entry of value) {
    if (typeof entry === 'object' && entry !== null && 'id' in entry) {
      const record: Record<string, unknown> = { ...entry };
      if (typeof record.id === 'string') {
        blocks.push({
          id: record.id,
          name: typeof record.name === 'string' ? record.name : undefined,
          description: typeof record.description === 'string' ? record.description : undefined,
          category: typeof record.category === 'string' ? record.category : undefined,
        });
      }
    }
  }
  return blocks;
}

/** Blocks as the running hub sees them, keyed by local block id. Best-effort. */
async function fetchHubBlocks(pluginName: string): Promise<Map<string, HubBlock>> {
  const map = new Map<string, HubBlock>();
  try {
    const res = await fetch(`${hubOrigin()}/api/blocks`, { signal: AbortSignal.timeout(2000) });
    if (!res.ok) {
      return map;
    }
    const body: unknown = await res.json();
    if (!Array.isArray(body)) {
      return map;
    }
    for (const entry of body) {
      if (typeof entry !== 'object' || entry === null) {
        continue;
      }
      const record: Record<string, unknown> = { ...entry };
      if (record.pluginId !== pluginName || typeof record.id !== 'string') {
        continue;
      }
      const localId = record.id.split(':').pop() ?? record.id;
      map.set(localId, {
        id: localId,
        inputs: Array.isArray(record.inputs) ? record.inputs : [],
        outputs: Array.isArray(record.outputs) ? record.outputs : [],
      });
    }
  } catch {
    // Hub unreachable: manifest-only docs.
  }
  return map;
}

function portList(ports: HubPort[] | undefined): string {
  if (!ports || ports.length === 0) {
    return 'none';
  }
  return ports.map((p) => `\`${p.id}\``).join(', ');
}

function renderMarkdown(
  pluginName: string,
  blocks: ManifestBlock[],
  hubBlocks: Map<string, HubBlock>
): string {
  const lines: string[] = [
    `# ${pluginName} blocks`,
    '',
    '<!-- Generated by `brika docs`. Do not edit by hand. -->',
    '',
  ];
  const byCategory = new Map<string, ManifestBlock[]>();
  for (const block of blocks) {
    const category = block.category ?? 'other';
    const list = byCategory.get(category) ?? [];
    list.push(block);
    byCategory.set(category, list);
  }
  for (const [category, group] of [...byCategory.entries()].sort(([a], [b]) =>
    a.localeCompare(b)
  )) {
    lines.push(`## ${category.charAt(0).toUpperCase()}${category.slice(1)}`, '');
    for (const block of group) {
      lines.push(`### ${block.name ?? block.id}`, '');
      lines.push(`- id: \`${block.id}\``);
      if (block.description) {
        lines.push(`- ${block.description}`);
      }
      const live = hubBlocks.get(block.id);
      if (live) {
        lines.push(`- inputs: ${portList(live.inputs)}`);
        lines.push(`- outputs: ${portList(live.outputs)}`);
      }
      lines.push('');
    }
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

export default defineCommand({
  name: 'docs',
  description: 'Generate BLOCKS.md from the plugin manifest (hub-enriched when running)',
  details:
    'Reads package.json `blocks[]` and writes BLOCKS.md at the plugin root. When the local hub ' +
    'is running with this plugin loaded, each block also lists its input/output ports.',
  examples: ['brika docs'],
  async handler() {
    const root = process.cwd();
    const manifestPath = join(root, 'package.json');
    if (!existsSync(manifestPath)) {
      process.stderr.write('No package.json here. Run from the plugin root.\n');
      process.exitCode = 1;
      return;
    }
    const parsed: unknown = JSON.parse(await readFile(manifestPath, 'utf8'));
    if (typeof parsed !== 'object' || parsed === null) {
      process.stderr.write('package.json is not an object.\n');
      process.exitCode = 1;
      return;
    }
    const manifest: Record<string, unknown> = { ...parsed };
    const pluginName = typeof manifest.name === 'string' ? manifest.name : 'plugin';
    const blocks = asManifestBlocks(manifest.blocks);
    if (blocks.length === 0) {
      process.stderr.write('No blocks declared in package.json blocks[]; nothing to document.\n');
      process.exitCode = 1;
      return;
    }

    const hubUp = await pingHub();
    const hubBlocks = hubUp ? await fetchHubBlocks(pluginName) : new Map<string, HubBlock>();

    const outPath = join(root, 'BLOCKS.md');
    await writeFile(outPath, renderMarkdown(pluginName, blocks, hubBlocks));
    const enrichment = hubBlocks.size > 0 ? ' (hub-enriched with ports)' : ' (manifest only)';
    process.stdout.write(`${pc.green('wrote')} BLOCKS.md, ${blocks.length} blocks${enrichment}\n`);
  },
});
