/**
 * Generates the committed `src/_generated/entry.ts` for `brika build`. The entry
 * is the plugin's `package.json` `main`: importing it side-effect-imports every
 * server module so their `define*()` registrations run. It replaces the
 * hand-maintained `src/index.tsx` barrel.
 */

import { join, resolve } from 'node:path';
import { actionFiles, blockFiles, firstExisting, sparkFiles, toolFiles, toSpecifier } from './scan';

const ENTRY_HEADER = `// Generated by \`brika build\`. Do not edit.
// package.json "main" points here; importing each module runs its define*()
// registration (blocks, sparks, actions, tools) and the plugin lifecycle.`;

/**
 * Build the `src/_generated/entry.ts` content: side-effect imports of every
 * server module (blocks, sparks, actions, tools) plus the optional lifecycle
 * file `src/plugin.ts`. Browser modules (bricks/pages) are deliberately never
 * imported here: they would pull React into the isolated plugin subprocess.
 */
export async function generateEntry(pluginRoot: string): Promise<string> {
  const root = resolve(pluginRoot);
  const entryDir = join(root, 'src', '_generated');
  const [blocks, sparks, actions, tools] = await Promise.all([
    blockFiles(root),
    sparkFiles(root),
    actionFiles(root),
    toolFiles(root),
  ]);
  const lifecycle = await firstExisting(root, ['src/plugin.ts', 'src/plugin.tsx']);

  const specifiers = [...blocks, ...sparks, ...actions, ...tools]
    .sort((a, b) => a.localeCompare(b))
    .map((file) => toSpecifier(entryDir, file));
  if (lifecycle !== undefined) {
    specifiers.push(toSpecifier(entryDir, lifecycle));
  }

  const lines = specifiers.map((specifier) => `import '${specifier}';`);
  return `${ENTRY_HEADER}\n${lines.join('\n')}\n`;
}
