id = "workflow-mk4avg3n"
name = "New Workflow lol"
enabled = true

[[blocks]]
id = "clock-mk4aw72g-3"
type = "@brika/blocks-builtin:clock"

[blocks.config]
interval = 5000

[blocks.position]
x = -43.89848171284386
y = -255.75773882010998

[[blocks]]
id = "split-mk4duszi-1"
type = "@brika/blocks-builtin:split"

[blocks.config]
id = "split-mk4duszi-1"
type = "@brika/blocks-builtin:split"

[blocks.position]
x = -88.22992883964521
y = -151.4745834219946

[[blocks]]
id = "delay-mk4dv520-2"
type = "@brika/blocks-builtin:delay"

[blocks.config]
id = "delay-mk4dv520-2"
type = "@brika/blocks-builtin:delay"
duration = 500

[blocks.position]
x = 173
y = 121

[[blocks]]
id = "log-mk4dvc04-3"
type = "@brika/blocks-builtin:log"

[blocks.config]
id = "log-mk4dvc04-3"
type = "@brika/blocks-builtin:log"
message = "Delayed: {{inputs.in.count}} at {{inputs.in.ts}}"

[blocks.position]
x = 128.08349831505188
y = 290.3562250772467

[[blocks]]
id = "log-mkd8p5p4-1"
type = "@brika/blocks-builtin:log"

[blocks.config]
id = "log-mkd8p5p4-1"
type = "@brika/blocks-builtin:log"
message = "{{config.level}}"
level = "error"

[blocks.position]
x = -160.20020267230242
y = 88.6681581777447

[[blocks]]
id = "http-request-mkg0oj9x-1"
type = "@brika/blocks-builtin:http-request"

[blocks.config]
id = "http-request-mkg0oj9x-1"
type = "@brika/blocks-builtin:http-request"
url = "http://google.com"
method = "GET"

[blocks.config.headers]
[blocks.position]
x = -485.1509238247687
y = 24.2037746212836

[[connections]]
from = "clock-mk4aw72g-3"
fromPort = "tick"
to = "split-mk4duszi-1"
toPort = "in"

[[connections]]
from = "split-mk4duszi-1"
fromPort = "b"
to = "delay-mk4dv520-2"
toPort = "in"

[[connections]]
from = "delay-mk4dv520-2"
fromPort = "out"
to = "log-mk4dvc04-3"
toPort = "in"

[[connections]]
from = "split-mk4duszi-1"
fromPort = "a"
to = "log-mkd8p5p4-1"
toPort = "in"

[[connections]]
from = "log-mkd8p5p4-1"
fromPort = "out"
to = "log-mk4dvc04-3"
toPort = "in"

[[connections]]
from = "split-mk4duszi-1"
fromPort = "a"
to = "http-request-mkg0oj9x-1"
toPort = "trigger"
