id = "workflow-mkd9hayo"
name = "New Workflow"
enabled = true

[[blocks]]
id = "spark-receiver-mklnz3d9-1"
type = "@brika/blocks-builtin:spark-receiver"

[blocks.config]
id = "spark-receiver-mklnz3d9-1"
type = "@brika/blocks-builtin:spark-receiver"
sparkType = "@brika/plugin-timer:countdown-completed"

[blocks.position]
x = -152.26566418326348
y = -316.6903465229952

[[blocks]]
id = "split-mklq6lzl-1"
type = "@brika/blocks-builtin:split"

[blocks.config]
id = "split-mklq6lzl-1"
type = "@brika/blocks-builtin:split"

[blocks.position]
x = -57.88174347087505
y = -145.36093840126404

[[blocks]]
id = "end-mklq6zum-2"
type = "@brika/blocks-builtin:end"

[blocks.config]
id = "end-mklq6zum-2"
type = "@brika/blocks-builtin:end"

[blocks.position]
x = -173.15140906912853
y = 110.31539866356997

[[blocks]]
id = "end-mklq71yk-3"
type = "@brika/blocks-builtin:end"

[blocks.config]
id = "end-mklq71yk-3"
type = "@brika/blocks-builtin:end"

[blocks.position]
x = 67.88395391823754
y = 22.71736569425631

[[blocks]]
id = "delay-mklq7gsz-4"
type = "@brika/blocks-builtin:delay"

[blocks.config]
id = "delay-mklq7gsz-4"
type = "@brika/blocks-builtin:delay"
duration = 500

[blocks.position]
x = -135.67058821495357
y = -32.79230565461165

[[connections]]
from = "spark-receiver-mklnz3d9-1"
fromPort = "out"
to = "split-mklq6lzl-1"
toPort = "in"

[[connections]]
from = "split-mklq6lzl-1"
fromPort = "b"
to = "end-mklq71yk-3"
toPort = "in"

[[connections]]
from = "split-mklq6lzl-1"
fromPort = "a"
to = "delay-mklq7gsz-4"
toPort = "in"

[[connections]]
from = "delay-mklq7gsz-4"
fromPort = "out"
to = "end-mklq6zum-2"
toPort = "in"
