/**
 * Layer 1 — Color roles
 * Themes typically override these. Listed in the order they appear in
 * existing presets to make migration mechanical.
 */

import type { TokenSpec } from '../types';

export const COLOR_ROLES: readonly TokenSpec[] = [
  {
    name: 'background',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.99 0 0)',
    defaultDark: 'oklch(0.14 0.02 260)',
    description: 'Page background. The base canvas every surface sits on.',
    themePath: 'colors.background',
    tailwindNamespace: 'color',
  },
  {
    name: 'foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.15 0.01 260)',
    defaultDark: 'oklch(0.96 0.01 260)',
    description: 'Default text color, paired with `background`.',
    themePath: 'colors.foreground',
    tailwindNamespace: 'color',
  },
  {
    name: 'card',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(1 0 0)',
    defaultDark: 'oklch(0.17 0.02 260)',
    description: 'Background for resting cards and panels.',
    themePath: 'colors.card',
    tailwindNamespace: 'color',
  },
  {
    name: 'card-foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.15 0.01 260)',
    defaultDark: 'oklch(0.96 0.01 260)',
    description: 'Text color for content inside cards.',
    themePath: 'colors.cardForeground',
    tailwindNamespace: 'color',
  },
  {
    name: 'popover',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(1 0 0)',
    defaultDark: 'oklch(0.17 0.02 260)',
    description: 'Background for floating surfaces (popovers, dropdowns, tooltips).',
    themePath: 'colors.popover',
    tailwindNamespace: 'color',
  },
  {
    name: 'popover-foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.15 0.01 260)',
    defaultDark: 'oklch(0.96 0.01 260)',
    description: 'Text color for content inside popovers.',
    themePath: 'colors.popoverForeground',
    tailwindNamespace: 'color',
  },
  {
    name: 'primary',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.55 0.18 265)',
    defaultDark: 'oklch(0.7 0.16 265)',
    description: 'Brand primary. Used for filled buttons, focus ring, links.',
    themePath: 'colors.primary',
    tailwindNamespace: 'color',
  },
  {
    name: 'primary-foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.99 0 0)',
    defaultDark: 'oklch(0.14 0.02 260)',
    description: 'Text color that reads on `primary` backgrounds.',
    themePath: 'colors.primaryForeground',
    tailwindNamespace: 'color',
  },
  {
    name: 'secondary',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.94 0.005 260)',
    defaultDark: 'oklch(0.22 0.02 260)',
    description: 'Secondary surfaces and quiet button fills.',
    themePath: 'colors.secondary',
    tailwindNamespace: 'color',
  },
  {
    name: 'secondary-foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.15 0.01 260)',
    defaultDark: 'oklch(0.96 0.01 260)',
    description: 'Text color paired with `secondary`.',
    themePath: 'colors.secondaryForeground',
    tailwindNamespace: 'color',
  },
  {
    name: 'muted',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.95 0.005 260)',
    defaultDark: 'oklch(0.2 0.02 260)',
    description: 'Subdued surface for placeholder content and inactive rails.',
    themePath: 'colors.muted',
    tailwindNamespace: 'color',
  },
  {
    name: 'muted-foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.5 0.01 260)',
    defaultDark: 'oklch(0.65 0.02 260)',
    description: 'De-emphasized text (helper copy, captions, placeholders).',
    themePath: 'colors.mutedForeground',
    tailwindNamespace: 'color',
  },
  {
    name: 'accent',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.92 0.01 260)',
    defaultDark: 'oklch(0.25 0.02 260)',
    description: 'Hover/highlight surface for interactive items in menus and lists.',
    themePath: 'colors.accent',
    tailwindNamespace: 'color',
  },
  {
    name: 'accent-foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.15 0.01 260)',
    defaultDark: 'oklch(0.96 0.01 260)',
    description: 'Text color paired with `accent`.',
    themePath: 'colors.accentForeground',
    tailwindNamespace: 'color',
  },
  {
    name: 'border',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.9 0.01 260)',
    defaultDark: 'oklch(0.25 0.02 260)',
    description: 'Default border color across the system.',
    themePath: 'colors.border',
    tailwindNamespace: 'color',
  },
  {
    name: 'input',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.9 0.01 260)',
    defaultDark: 'oklch(0.25 0.02 260)',
    description: 'Border color for input controls (input, select, textarea).',
    themePath: 'colors.input',
    tailwindNamespace: 'color',
  },
  {
    name: 'ring',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.55 0.18 265)',
    defaultDark: 'oklch(0.7 0.16 265)',
    description: 'Focus ring color. Defaults to `primary`.',
    themePath: 'colors.ring',
    tailwindNamespace: 'color',
  },

  // Feedback
  {
    name: 'success',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.55 0.16 145)',
    defaultDark: 'oklch(0.72 0.15 145)',
    description: 'Positive feedback (success toasts, confirmation states).',
    themePath: 'colors.success',
    tailwindNamespace: 'color',
  },
  {
    name: 'success-foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.99 0 0)',
    defaultDark: 'oklch(0.14 0.02 260)',
    description: 'Text color paired with `success`.',
    themePath: 'colors.successForeground',
    tailwindNamespace: 'color',
  },
  {
    name: 'warning',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.65 0.14 85)',
    defaultDark: 'oklch(0.8 0.15 85)',
    description: 'Cautionary feedback (warning banners, caution states).',
    themePath: 'colors.warning',
    tailwindNamespace: 'color',
  },
  {
    name: 'warning-foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.15 0.01 260)',
    defaultDark: 'oklch(0.14 0.02 260)',
    description: 'Text color paired with `warning`.',
    themePath: 'colors.warningForeground',
    tailwindNamespace: 'color',
  },
  {
    name: 'info',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.5 0.18 230)',
    defaultDark: 'oklch(0.72 0.12 230)',
    description: 'Informational feedback (tips, notes, neutral accents).',
    themePath: 'colors.info',
    tailwindNamespace: 'color',
  },
  {
    name: 'info-foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.99 0 0)',
    defaultDark: 'oklch(0.14 0.02 260)',
    description: 'Text color paired with `info`.',
    themePath: 'colors.infoForeground',
    tailwindNamespace: 'color',
  },
  {
    name: 'destructive',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.55 0.22 25)',
    defaultDark: 'oklch(0.65 0.2 25)',
    description: 'Destructive actions (delete buttons, error states).',
    themePath: 'colors.destructive',
    tailwindNamespace: 'color',
  },
  {
    name: 'destructive-foreground',
    layer: 'role',
    category: 'color',
    defaultLight: 'oklch(0.99 0 0)',
    defaultDark: 'oklch(0.96 0.01 260)',
    description: 'Text color paired with `destructive`.',
    themePath: 'colors.destructiveForeground',
    tailwindNamespace: 'color',
  },
];
