// Generated by `brika build`. Do not edit.
// package.json "main" points here; importing each module runs its define*()
// registration (blocks, sparks, actions, tools) and the plugin lifecycle.
import '../blocks/agent';
import '../blocks/call-tool';
import '../blocks/llm';
import '../tools/ask-claude';
import '../plugin';
