/**
 * Workflow diagnostic codes — these are NEVER thrown as errors.
 * They flow through validation pipelines (`@brika/workflow`) as
 * structured diagnostics; the catalog provides their severity + i18n
 * key for UI display. Hence no factory entry in `factories.ts`.
 */

import { entry, TYPE_BASE } from './_entry';

export const WorkflowCatalog = {
  WORKFLOW_UNKNOWN_BLOCK_TYPE: entry({
    title: 'Unknown block type',
    description: 'Block references a type not in the registry.',
    typeUri: `${TYPE_BASE}workflow/unknown-block-type`,
    status: 400,
    severity: 'error',
    category: 'workflow',
    retryable: false,
    transient: false,
    data: undefined,
    message: () => 'Unknown block type.',
  }),
  WORKFLOW_UNKNOWN_OUTPUT_PORT: entry({
    title: 'Unknown output port',
    description: 'Block declares an output port not on its type.',
    typeUri: `${TYPE_BASE}workflow/unknown-output-port`,
    status: 400,
    severity: 'error',
    category: 'workflow',
    retryable: false,
    transient: false,
    data: undefined,
    message: () => 'Unknown output port.',
  }),
  WORKFLOW_UNKNOWN_INPUT_PORT: entry({
    title: 'Unknown input port',
    description: 'Block declares an input port not on its type.',
    typeUri: `${TYPE_BASE}workflow/unknown-input-port`,
    status: 400,
    severity: 'error',
    category: 'workflow',
    retryable: false,
    transient: false,
    data: undefined,
    message: () => 'Unknown input port.',
  }),
  WORKFLOW_UNKNOWN_TARGET_BLOCK_TYPE: entry({
    title: 'Unknown target block type',
    description: 'A connection target block has an unknown type.',
    typeUri: `${TYPE_BASE}workflow/unknown-target-block-type`,
    status: 400,
    severity: 'error',
    category: 'workflow',
    retryable: false,
    transient: false,
    data: undefined,
    message: () => 'Unknown target block type.',
  }),
  WORKFLOW_INVALID_PORT_REF: entry({
    title: 'Invalid port reference',
    description: 'Port reference string is malformed.',
    typeUri: `${TYPE_BASE}workflow/invalid-port-ref`,
    status: 400,
    severity: 'error',
    category: 'workflow',
    retryable: false,
    transient: false,
    data: undefined,
    message: () => 'Invalid port reference.',
  }),
  WORKFLOW_TARGET_BLOCK_NOT_FOUND: entry({
    title: 'Target block not found',
    description: 'A connection target block id does not exist.',
    typeUri: `${TYPE_BASE}workflow/target-block-not-found`,
    status: 400,
    severity: 'error',
    category: 'workflow',
    retryable: false,
    transient: false,
    data: undefined,
    message: () => 'Target block not found.',
  }),
  WORKFLOW_SOURCE_BLOCK_NOT_FOUND: entry({
    title: 'Source block not found',
    description: 'A connection source block id does not exist.',
    typeUri: `${TYPE_BASE}workflow/source-block-not-found`,
    status: 400,
    severity: 'error',
    category: 'workflow',
    retryable: false,
    transient: false,
    data: undefined,
    message: () => 'Source block not found.',
  }),
  WORKFLOW_TARGET_PORT_NOT_FOUND: entry({
    title: 'Target port not found',
    description: 'Target block has no port matching the connection target.',
    typeUri: `${TYPE_BASE}workflow/target-port-not-found`,
    status: 400,
    severity: 'error',
    category: 'workflow',
    retryable: false,
    transient: false,
    data: undefined,
    message: () => 'Target port not found.',
  }),
  WORKFLOW_INVALID_CONNECTION: entry({
    title: 'Invalid connection',
    description: 'Connection types are incompatible.',
    typeUri: `${TYPE_BASE}workflow/invalid-connection`,
    status: 400,
    severity: 'error',
    category: 'workflow',
    retryable: false,
    transient: false,
    data: undefined,
    message: () => 'Invalid connection.',
  }),
  WORKFLOW_MISSING_BIDIRECTIONAL_REF: entry({
    title: 'Missing bidirectional reference',
    description: 'Connection has only one side wired up.',
    typeUri: `${TYPE_BASE}workflow/missing-bidirectional-ref`,
    status: 400,
    severity: 'warning',
    category: 'workflow',
    retryable: false,
    transient: false,
    data: undefined,
    message: () => 'Connection is missing the bidirectional reference.',
  }),
  WORKFLOW_ORPHAN_BLOCK: entry({
    title: 'Orphan block',
    description: 'Block has input ports but no incoming connections.',
    typeUri: `${TYPE_BASE}workflow/orphan-block`,
    status: 400,
    severity: 'warning',
    category: 'workflow',
    retryable: false,
    transient: false,
    data: undefined,
    message: () => 'Block has input ports but no incoming connections.',
  }),
} as const;
