/**
 * Theme import / export helpers.
 * Export: serialize the current draft and trigger a file download.
 * Import: parse a JSON file, validate shape, return a new ThemeConfig
 * with a fresh id (so re-importing doesn't overwrite the original).
 */

import { cornerShapeKeyword, darkOverrideVars, themeToVars, varsToCssText } from './theme-css';
import { THEME_CONFIG_VERSION, type ThemeColors, type ThemeConfig } from './types';

function slugify(input: string): string {
  const compacted = input.toLowerCase().replaceAll(/[^a-z0-9]+/g, '-');
  const start = compacted.startsWith('-') ? 1 : 0;
  const end = compacted.endsWith('-') ? compacted.length - 1 : compacted.length;
  return compacted.slice(start, Math.max(start, end)).slice(0, 40);
}

export function exportThemeToFile(theme: ThemeConfig): void {
  const blob = new Blob([JSON.stringify(theme, null, 2)], {
    type: 'application/json',
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `brika-theme-${slugify(theme.name) || theme.id}.json`;
  a.click();
  URL.revokeObjectURL(url);
}

const REQUIRED_COLOR_TOKENS: readonly (keyof ThemeColors)[] = [
  'background',
  'foreground',
  'primary',
  'card',
  'border',
];

function isObject(v: unknown): v is Record<string, unknown> {
  return v !== null && typeof v === 'object';
}

function isThemeColors(v: unknown): v is ThemeColors {
  if (!isObject(v)) {
    return false;
  }
  return REQUIRED_COLOR_TOKENS.every((k) => typeof v[k] === 'string');
}

function isThemeConfig(v: unknown): v is ThemeConfig {
  if (!isObject(v)) {
    return false;
  }
  if (v.version !== THEME_CONFIG_VERSION) {
    return false;
  }
  if (typeof v.name !== 'string' || typeof v.radius !== 'number') {
    return false;
  }
  if (!isObject(v.colors) || !isThemeColors(v.colors.light) || !isThemeColors(v.colors.dark)) {
    return false;
  }
  if (!isObject(v.fonts) || typeof v.fonts.sans !== 'string' || typeof v.fonts.mono !== 'string') {
    return false;
  }
  return true;
}

/** Build a plain CSS snippet so users can paste the theme into their own stylesheet. */
export function themeToCss(theme: ThemeConfig, selector = ':root'): string {
  const shape = cornerShapeKeyword(theme.corners);
  const light = varsToCssText(themeToVars(theme, 'light'));
  const dark = varsToCssText(darkOverrideVars(theme));
  const darkSelector = selector === ':root' ? '.dark:root' : `.dark${selector}`;

  return `/* ${theme.name} - generated by Brika theme builder */
${selector} {
  corner-shape: ${shape};
${light}
}

${darkSelector} {
${dark}
}
`;
}

export function exportThemeAsCss(theme: ThemeConfig): void {
  const css = themeToCss(theme);
  const blob = new Blob([css], { type: 'text/css' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `brika-theme-${slugify(theme.name) || theme.id}.css`;
  a.click();
  URL.revokeObjectURL(url);
}

export async function copyThemeCssToClipboard(theme: ThemeConfig): Promise<void> {
  await navigator.clipboard.writeText(themeToCss(theme));
}

export async function importThemeFromFile(file: File): Promise<ThemeConfig> {
  const text = await file.text();
  const parsed: unknown = JSON.parse(text);
  if (!isThemeConfig(parsed)) {
    throw new Error(
      'Invalid theme file — expected a Brika ThemeConfig with version, name, radius, fonts, and colors.light/dark.'
    );
  }
  const now = Date.now();
  return {
    ...parsed,
    id: `custom-${now.toString(36)}`,
    createdAt: now,
    updatedAt: now,
  };
}
