/**
 * Theme import / export helpers.
 * Export: serialize the current draft and trigger a file download.
 * Import: parse JSON, validate against `ThemeConfig`, and return a copy
 * with a fresh id (so re-importing doesn't overwrite the original).
 */

import { renderThemeStyleSheet } from '@brika/clay/themes';
import { recipesToFragments } from './recipes';
import { ThemeConfig } from './types';

function slugify(input: string): string {
  const compacted = input.toLowerCase().replaceAll(/[^a-z0-9]+/g, '-');
  const start = compacted.startsWith('-') ? 1 : 0;
  const end = compacted.endsWith('-') ? compacted.length - 1 : compacted.length;
  return compacted.slice(start, Math.max(start, end)).slice(0, 40);
}

export function exportThemeToFile(theme: ThemeConfig): void {
  const blob = new Blob([JSON.stringify(theme, null, 2)], {
    type: 'application/json',
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `brika-theme-${slugify(theme.name) || theme.id}.json`;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Build a plain CSS snippet users can paste into their own stylesheet.
 * Combines Clay's canonical stylesheet (light + dark blocks) with our
 * Brika-extension extras inside the same `:root` scope.
 */
export function themeToCss(theme: ThemeConfig): string {
  const clayCss = renderThemeStyleSheet(theme);
  const { extras } = recipesToFragments(theme.brika, theme.colors?.light?.primary);
  const extraEntries = Object.entries(extras);
  if (extraEntries.length === 0) {
    return `/* ${theme.name} — generated by Brika theme builder */\n${clayCss}\n`;
  }
  const extraLines = extraEntries.map(([k, v]) => `  ${k}: ${v};`).join('\n');
  const extrasBlock = `:root {\n${extraLines}\n}\n`;
  return `/* ${theme.name} — generated by Brika theme builder */\n${clayCss}\n${extrasBlock}`;
}

export function exportThemeAsCss(theme: ThemeConfig): void {
  const css = themeToCss(theme);
  const blob = new Blob([css], { type: 'text/css' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `brika-theme-${slugify(theme.name) || theme.id}.css`;
  a.click();
  URL.revokeObjectURL(url);
}

export async function copyThemeCssToClipboard(theme: ThemeConfig): Promise<void> {
  await navigator.clipboard.writeText(themeToCss(theme));
}

export async function importThemeFromFile(file: File): Promise<ThemeConfig> {
  const text = await file.text();
  const parsed: unknown = JSON.parse(text);
  const result = ThemeConfig.safeParse(parsed);
  if (!result.success) {
    throw new Error(
      'Invalid theme file — expected a Brika ThemeConfig with version, name, and colors.'
    );
  }
  const now = Date.now();
  return {
    ...result.data,
    id: `custom-${now.toString(36)}`,
    createdAt: now,
    updatedAt: now,
  };
}
