/**
 * Palette presets — quick-start themes the user can seed from.
 * Each preset is a light+dark palette plus optional radius/font tweaks.
 * Choosing a preset produces a fresh `ThemeConfig` so the user can iterate.
 */

import { DEFAULT_DARK, DEFAULT_LIGHT } from './tokens';
import type { CornerStyle, ThemeColors, ThemeConfig } from './types';
import { THEME_CONFIG_VERSION } from './types';

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  category: 'built-in' | 'curated';
  radius?: number;
  corners?: CornerStyle;
  fonts?: { sans?: string; mono?: string };
  colors: { light: ThemeColors; dark: ThemeColors };
  /** Small list of hex colors shown as a preview strip */
  accentSwatches: readonly string[];
}

function override(base: ThemeColors, patch: Partial<ThemeColors>): ThemeColors {
  return { ...base, ...patch };
}

export const THEME_PRESETS: readonly ThemePreset[] = [
  {
    id: 'default',
    name: 'Default',
    description: 'Brika classic — balanced blue, neutral greys.',
    category: 'built-in',
    accentSwatches: ['#4a63d1', '#35924a', '#c78a2b', '#c4422d'],
    colors: { light: DEFAULT_LIGHT, dark: DEFAULT_DARK },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    description: 'Cool blues and teals, calm surfaces.',
    category: 'built-in',
    accentSwatches: ['#1f6fd6', '#2f8fa8', '#2b9d8e', '#3ea0b3'],
    colors: {
      light: override(DEFAULT_LIGHT, {
        primary: '#1f6fd6',
        'primary-foreground': '#fbfeff',
        accent: '#cde6f2',
        'accent-foreground': '#0d2a3d',
        ring: '#1f6fd6',
        success: '#2b9d8e',
        info: '#1d6cb8',
        'data-1': '#1f6fd6',
        'data-2': '#3ea0b3',
        'data-7': '#2b9d8e',
      }),
      dark: override(DEFAULT_DARK, {
        primary: '#6ea7e8',
        'primary-foreground': '#0d1b24',
        accent: '#1c3447',
        'accent-foreground': '#e4f2fb',
        ring: '#6ea7e8',
        success: '#64c5b4',
        info: '#6ea7e8',
        'data-1': '#6ea7e8',
        'data-2': '#64b9c7',
        'data-7': '#64c5b4',
      }),
    },
  },
  {
    id: 'forest',
    name: 'Forest',
    description: 'Deep greens with warm earth accents.',
    category: 'built-in',
    accentSwatches: ['#2f7a3f', '#4a8c5a', '#9c7a4a', '#c78a2b'],
    colors: {
      light: override(DEFAULT_LIGHT, {
        primary: '#2f7a3f',
        'primary-foreground': '#fbfff3',
        accent: '#d6e5c7',
        'accent-foreground': '#1b2d19',
        ring: '#2f7a3f',
        success: '#2f7a3f',
        warning: '#a77932',
        'data-1': '#2f7a3f',
        'data-3': '#4a8c5a',
      }),
      dark: override(DEFAULT_DARK, {
        primary: '#75c18a',
        'primary-foreground': '#0f1d10',
        accent: '#1f2e20',
        'accent-foreground': '#e9f5e8',
        ring: '#75c18a',
        success: '#75c18a',
        'data-1': '#75c18a',
        'data-3': '#8bc99b',
      }),
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    description: 'Warm oranges, corals, amber highlights.',
    category: 'built-in',
    accentSwatches: ['#d87327', '#db9149', '#c44f3a', '#c78a2b'],
    colors: {
      light: override(DEFAULT_LIGHT, {
        primary: '#d87327',
        'primary-foreground': '#fff8f2',
        accent: '#fadfc7',
        'accent-foreground': '#3a1d0c',
        ring: '#d87327',
        warning: '#c78a2b',
        'data-2': '#d87327',
        'data-6': '#db9149',
      }),
      dark: override(DEFAULT_DARK, {
        primary: '#f2a269',
        'primary-foreground': '#1b0e05',
        accent: '#3a241a',
        'accent-foreground': '#fbe7d6',
        ring: '#f2a269',
        warning: '#f0be6e',
        'data-2': '#f2a269',
        'data-6': '#f0be6e',
      }),
    },
  },
  {
    id: 'lavender',
    name: 'Lavender',
    description: 'Soft purples and violets.',
    category: 'built-in',
    accentSwatches: ['#8055d4', '#a77be0', '#6d6ae0', '#c48ae0'],
    colors: {
      light: override(DEFAULT_LIGHT, {
        primary: '#8055d4',
        'primary-foreground': '#fbf6ff',
        accent: '#e4d8f5',
        'accent-foreground': '#2a1a3d',
        ring: '#8055d4',
        info: '#6d6ae0',
        'data-5': '#8055d4',
        'data-8': '#c48ae0',
      }),
      dark: override(DEFAULT_DARK, {
        primary: '#b69be8',
        'primary-foreground': '#160d24',
        accent: '#2b1f3b',
        'accent-foreground': '#ece3f8',
        ring: '#b69be8',
        info: '#9896ef',
        'data-5': '#b69be8',
        'data-8': '#d4a5e8',
      }),
    },
  },
  {
    id: 'ruby',
    name: 'Ruby',
    description: 'Bold reds, crimson accents.',
    category: 'built-in',
    accentSwatches: ['#c93458', '#d05a6a', '#c4422d', '#d6698a'],
    colors: {
      light: override(DEFAULT_LIGHT, {
        primary: '#c93458',
        'primary-foreground': '#fff4f7',
        accent: '#f5d3db',
        'accent-foreground': '#3d0f1c',
        ring: '#c93458',
        destructive: '#c4422d',
        'data-4': '#c93458',
        'data-8': '#d6698a',
      }),
      dark: override(DEFAULT_DARK, {
        primary: '#e37a93',
        'primary-foreground': '#200a10',
        accent: '#3d1a25',
        'accent-foreground': '#fae1e8',
        ring: '#e37a93',
        destructive: '#e06a55',
        'data-4': '#e37a93',
        'data-8': '#e7a4b9',
      }),
    },
  },
  // Curated extras
  {
    id: 'nord',
    name: 'Nord',
    description: 'Arctic, north-bluish palette.',
    category: 'curated',
    accentSwatches: ['#5e81ac', '#88c0d0', '#a3be8c', '#ebcb8b'],
    colors: {
      light: {
        background: '#eceff4',
        foreground: '#2e3440',
        card: '#ffffff',
        'card-foreground': '#2e3440',
        popover: '#ffffff',
        'popover-foreground': '#2e3440',
        primary: '#5e81ac',
        'primary-foreground': '#eceff4',
        secondary: '#e5e9f0',
        'secondary-foreground': '#2e3440',
        accent: '#d8dee9',
        'accent-foreground': '#2e3440',
        muted: '#e5e9f0',
        'muted-foreground': '#4c566a',
        border: '#d8dee9',
        input: '#d8dee9',
        ring: '#5e81ac',
        success: '#a3be8c',
        'success-foreground': '#2e3440',
        warning: '#ebcb8b',
        'warning-foreground': '#2e3440',
        info: '#88c0d0',
        'info-foreground': '#2e3440',
        destructive: '#bf616a',
        'destructive-foreground': '#eceff4',
        'data-1': '#5e81ac',
        'data-2': '#d08770',
        'data-3': '#a3be8c',
        'data-4': '#bf616a',
        'data-5': '#b48ead',
        'data-6': '#ebcb8b',
        'data-7': '#88c0d0',
        'data-8': '#8fbcbb',
      },
      dark: {
        background: '#2e3440',
        foreground: '#eceff4',
        card: '#3b4252',
        'card-foreground': '#eceff4',
        popover: '#3b4252',
        'popover-foreground': '#eceff4',
        primary: '#88c0d0',
        'primary-foreground': '#2e3440',
        secondary: '#434c5e',
        'secondary-foreground': '#eceff4',
        accent: '#4c566a',
        'accent-foreground': '#eceff4',
        muted: '#3b4252',
        'muted-foreground': '#a9b3c7',
        border: '#434c5e',
        input: '#434c5e',
        ring: '#88c0d0',
        success: '#a3be8c',
        'success-foreground': '#2e3440',
        warning: '#ebcb8b',
        'warning-foreground': '#2e3440',
        info: '#8fbcbb',
        'info-foreground': '#2e3440',
        destructive: '#bf616a',
        'destructive-foreground': '#eceff4',
        'data-1': '#88c0d0',
        'data-2': '#d08770',
        'data-3': '#a3be8c',
        'data-4': '#bf616a',
        'data-5': '#b48ead',
        'data-6': '#ebcb8b',
        'data-7': '#8fbcbb',
        'data-8': '#81a1c1',
      },
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    description: 'Vibrant dark palette, neon accents.',
    category: 'curated',
    accentSwatches: ['#bd93f9', '#ff79c6', '#50fa7b', '#ffb86c'],
    colors: {
      light: {
        background: '#f8f8f2',
        foreground: '#282a36',
        card: '#ffffff',
        'card-foreground': '#282a36',
        popover: '#ffffff',
        'popover-foreground': '#282a36',
        primary: '#7c3aed',
        'primary-foreground': '#ffffff',
        secondary: '#ebebe4',
        'secondary-foreground': '#282a36',
        accent: '#e8dcf7',
        'accent-foreground': '#282a36',
        muted: '#ebebe4',
        'muted-foreground': '#5a5d70',
        border: '#d8d8d0',
        input: '#d8d8d0',
        ring: '#7c3aed',
        success: '#16a34a',
        'success-foreground': '#ffffff',
        warning: '#d97706',
        'warning-foreground': '#282a36',
        info: '#0ea5e9',
        'info-foreground': '#ffffff',
        destructive: '#dc2626',
        'destructive-foreground': '#ffffff',
        'data-1': '#7c3aed',
        'data-2': '#d97706',
        'data-3': '#16a34a',
        'data-4': '#dc2626',
        'data-5': '#db2777',
        'data-6': '#ca8a04',
        'data-7': '#0891b2',
        'data-8': '#c026d3',
      },
      dark: {
        background: '#282a36',
        foreground: '#f8f8f2',
        card: '#343746',
        'card-foreground': '#f8f8f2',
        popover: '#343746',
        'popover-foreground': '#f8f8f2',
        primary: '#bd93f9',
        'primary-foreground': '#282a36',
        secondary: '#44475a',
        'secondary-foreground': '#f8f8f2',
        accent: '#6272a4',
        'accent-foreground': '#f8f8f2',
        muted: '#343746',
        'muted-foreground': '#a8acc2',
        border: '#44475a',
        input: '#44475a',
        ring: '#bd93f9',
        success: '#50fa7b',
        'success-foreground': '#282a36',
        warning: '#f1fa8c',
        'warning-foreground': '#282a36',
        info: '#8be9fd',
        'info-foreground': '#282a36',
        destructive: '#ff5555',
        'destructive-foreground': '#f8f8f2',
        'data-1': '#bd93f9',
        'data-2': '#ffb86c',
        'data-3': '#50fa7b',
        'data-4': '#ff5555',
        'data-5': '#ff79c6',
        'data-6': '#f1fa8c',
        'data-7': '#8be9fd',
        'data-8': '#ff92d0',
      },
    },
  },
  {
    id: 'solarized',
    name: 'Solarized',
    description: 'Precision colors for machines and people.',
    category: 'curated',
    accentSwatches: ['#268bd2', '#2aa198', '#859900', '#cb4b16'],
    colors: {
      light: {
        background: '#fdf6e3',
        foreground: '#586e75',
        card: '#fffaf0',
        'card-foreground': '#586e75',
        popover: '#fffaf0',
        'popover-foreground': '#586e75',
        primary: '#268bd2',
        'primary-foreground': '#fdf6e3',
        secondary: '#eee8d5',
        'secondary-foreground': '#586e75',
        accent: '#eee8d5',
        'accent-foreground': '#586e75',
        muted: '#eee8d5',
        'muted-foreground': '#93a1a1',
        border: '#e0d8bd',
        input: '#e0d8bd',
        ring: '#268bd2',
        success: '#859900',
        'success-foreground': '#fdf6e3',
        warning: '#b58900',
        'warning-foreground': '#fdf6e3',
        info: '#2aa198',
        'info-foreground': '#fdf6e3',
        destructive: '#dc322f',
        'destructive-foreground': '#fdf6e3',
        'data-1': '#268bd2',
        'data-2': '#cb4b16',
        'data-3': '#859900',
        'data-4': '#dc322f',
        'data-5': '#6c71c4',
        'data-6': '#b58900',
        'data-7': '#2aa198',
        'data-8': '#d33682',
      },
      dark: {
        background: '#002b36',
        foreground: '#93a1a1',
        card: '#073642',
        'card-foreground': '#93a1a1',
        popover: '#073642',
        'popover-foreground': '#93a1a1',
        primary: '#268bd2',
        'primary-foreground': '#002b36',
        secondary: '#073642',
        'secondary-foreground': '#93a1a1',
        accent: '#094352',
        'accent-foreground': '#93a1a1',
        muted: '#073642',
        'muted-foreground': '#839496',
        border: '#0f4c5c',
        input: '#0f4c5c',
        ring: '#268bd2',
        success: '#859900',
        'success-foreground': '#002b36',
        warning: '#b58900',
        'warning-foreground': '#002b36',
        info: '#2aa198',
        'info-foreground': '#002b36',
        destructive: '#dc322f',
        'destructive-foreground': '#fdf6e3',
        'data-1': '#268bd2',
        'data-2': '#cb4b16',
        'data-3': '#859900',
        'data-4': '#dc322f',
        'data-5': '#6c71c4',
        'data-6': '#b58900',
        'data-7': '#2aa198',
        'data-8': '#d33682',
      },
    },
  },
  {
    id: 'mono',
    name: 'Mono',
    description: 'Pure greyscale, bevelled corners.',
    category: 'curated',
    accentSwatches: ['#111111', '#444444', '#888888', '#cccccc'],
    radius: 0.25,
    corners: 'bevel',
    colors: {
      light: {
        background: '#ffffff',
        foreground: '#111111',
        card: '#ffffff',
        'card-foreground': '#111111',
        popover: '#ffffff',
        'popover-foreground': '#111111',
        primary: '#111111',
        'primary-foreground': '#ffffff',
        secondary: '#f2f2f2',
        'secondary-foreground': '#111111',
        accent: '#ebebeb',
        'accent-foreground': '#111111',
        muted: '#f2f2f2',
        'muted-foreground': '#6b6b6b',
        border: '#e2e2e2',
        input: '#e2e2e2',
        ring: '#111111',
        success: '#1f7a3a',
        'success-foreground': '#ffffff',
        warning: '#9a7000',
        'warning-foreground': '#ffffff',
        info: '#0e4b9c',
        'info-foreground': '#ffffff',
        destructive: '#9c1e1e',
        'destructive-foreground': '#ffffff',
        'data-1': '#111111',
        'data-2': '#333333',
        'data-3': '#555555',
        'data-4': '#777777',
        'data-5': '#999999',
        'data-6': '#b4b4b4',
        'data-7': '#d0d0d0',
        'data-8': '#888888',
      },
      dark: {
        background: '#0b0b0b',
        foreground: '#f2f2f2',
        card: '#131313',
        'card-foreground': '#f2f2f2',
        popover: '#131313',
        'popover-foreground': '#f2f2f2',
        primary: '#f2f2f2',
        'primary-foreground': '#0b0b0b',
        secondary: '#1c1c1c',
        'secondary-foreground': '#f2f2f2',
        accent: '#262626',
        'accent-foreground': '#f2f2f2',
        muted: '#1c1c1c',
        'muted-foreground': '#a0a0a0',
        border: '#2a2a2a',
        input: '#2a2a2a',
        ring: '#f2f2f2',
        success: '#4ea86d',
        'success-foreground': '#0b0b0b',
        warning: '#d5a53a',
        'warning-foreground': '#0b0b0b',
        info: '#68a0e6',
        'info-foreground': '#0b0b0b',
        destructive: '#e06a55',
        'destructive-foreground': '#0b0b0b',
        'data-1': '#f2f2f2',
        'data-2': '#d0d0d0',
        'data-3': '#b4b4b4',
        'data-4': '#999999',
        'data-5': '#777777',
        'data-6': '#555555',
        'data-7': '#333333',
        'data-8': '#a0a0a0',
      },
    },
  },
  {
    id: 'candy',
    name: 'Candy',
    description: 'Playful pastels, squircle corners.',
    category: 'curated',
    accentSwatches: ['#ff8fb1', '#b59bff', '#7ad0f4', '#ffd166'],
    radius: 1.25,
    corners: 'squircle',
    colors: {
      light: {
        background: '#fff7fb',
        foreground: '#382a40',
        card: '#ffffff',
        'card-foreground': '#382a40',
        popover: '#ffffff',
        'popover-foreground': '#382a40',
        primary: '#ff5c9c',
        'primary-foreground': '#ffffff',
        secondary: '#f7e6f0',
        'secondary-foreground': '#382a40',
        accent: '#ece0ff',
        'accent-foreground': '#382a40',
        muted: '#fbeaf2',
        'muted-foreground': '#7a6b8a',
        border: '#f1d7e4',
        input: '#f1d7e4',
        ring: '#ff5c9c',
        success: '#21a179',
        'success-foreground': '#ffffff',
        warning: '#e69524',
        'warning-foreground': '#ffffff',
        info: '#3aa0e3',
        'info-foreground': '#ffffff',
        destructive: '#ef476f',
        'destructive-foreground': '#ffffff',
        'data-1': '#ff5c9c',
        'data-2': '#ffb86c',
        'data-3': '#21a179',
        'data-4': '#ef476f',
        'data-5': '#8a67e0',
        'data-6': '#ffd166',
        'data-7': '#3aa0e3',
        'data-8': '#d66dbf',
      },
      dark: {
        background: '#1e1a28',
        foreground: '#f9eaf4',
        card: '#2a2438',
        'card-foreground': '#f9eaf4',
        popover: '#2a2438',
        'popover-foreground': '#f9eaf4',
        primary: '#ff8fb1',
        'primary-foreground': '#2a1a28',
        secondary: '#3a2e48',
        'secondary-foreground': '#f9eaf4',
        accent: '#4a3a60',
        'accent-foreground': '#f9eaf4',
        muted: '#2f2840',
        'muted-foreground': '#b9aecb',
        border: '#3d3250',
        input: '#3d3250',
        ring: '#ff8fb1',
        success: '#5cd4a6',
        'success-foreground': '#1a2a22',
        warning: '#ffd166',
        'warning-foreground': '#1e1a28',
        info: '#7ad0f4',
        'info-foreground': '#1e1a28',
        destructive: '#ff6f8b',
        'destructive-foreground': '#1e1a28',
        'data-1': '#ff8fb1',
        'data-2': '#ffbb85',
        'data-3': '#5cd4a6',
        'data-4': '#ff6f8b',
        'data-5': '#b59bff',
        'data-6': '#ffd166',
        'data-7': '#7ad0f4',
        'data-8': '#e392d4',
      },
    },
  },
] as const;

/** Build a fresh ThemeConfig from a preset. Generates new id + timestamps. */
export function createThemeFromPreset(
  preset: ThemePreset,
  name?: string,
  sansFont?: string,
  monoFont?: string
): ThemeConfig {
  const now = Date.now();
  return {
    version: THEME_CONFIG_VERSION,
    id: `custom-${now.toString(36)}`,
    name: name ?? preset.name,
    createdAt: now,
    updatedAt: now,
    radius: preset.radius ?? 0.75,
    corners: preset.corners ?? 'round',
    fonts: {
      sans: preset.fonts?.sans ?? sansFont ?? 'Inter, ui-sans-serif, system-ui, sans-serif',
      mono:
        preset.fonts?.mono ??
        monoFont ??
        '"JetBrains Mono", ui-monospace, SFMono-Regular, monospace',
    },
    colors: {
      light: { ...preset.colors.light },
      dark: { ...preset.colors.dark },
    },
  };
}
