// Generated by `brika build`. Do not edit.
// package.json "main" points here; importing each module runs its define*()
// registration (blocks, sparks, actions) and the plugin lifecycle.
import '../blocks/countdown';
import '../blocks/timer';
import '../sparks';
import '../plugin';
